# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInQuoteCond.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Def.XUseInQuoteCond.Inner
      import Src.Def.XUseInQuoteCond.Helpers, warn: false
      defp src_def_x_use_in_quote_cond_hidden(x), do: x
      cond do
        Code.ensure_loaded?(Kernel) ->
        def src_def_x_use_in_quote_cond_snoc(q), do: {q}
        def src_def_x_use_in_quote_cond_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
