# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseQuoteLocationKeep.Helpers do
  def src_defp_x_use_quote_location_keep_helper(x), do: x

  def target_marker, do: :ok
end
