# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XModuledocSince do
  @moduledoc "The documented module."
  @moduledoc since: "1.0.0"

  def src_def_x_moduledoc_since_snoc(q, x), do: {q, x}

  def local_site(a, b), do: src_def_x_moduledoc_since_snoc(a, b) # @local

  def module_local, do: Src.Def.XModuledocSince # @module_local
end
