# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInQuoteRescue.Helpers do
  def src_def_x_use_in_quote_rescue_helper(x), do: x

  def target_marker, do: :ok
end
