# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseInTryAfter do
  try do
    nil
  after
    use Src.Defmacrop.XUseInTryAfter.Injector
  end

  def local_site(a, b), do: src_defmacrop_x_use_in_try_after_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defmacrop_x_use_in_try_after_snoc(a), # @uses_0
      a,
      b
    }
  end
end
