# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateDoc.W1 do
  @doc "Appends x to q, as the delegating module documents it."
  defdelegate src_defdelegate_doc_w1_snoc(q, x), to: Src.DefdelegateDoc.W1.Target

  def local_site(a, b), do: src_defdelegate_doc_w1_snoc(a, b) # @local
end
