# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInQuoteRescue.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacro.XUseInQuoteRescue.Inner
      import Src.Defmacro.XUseInQuoteRescue.Helpers, warn: false
      defp src_defmacro_x_use_in_quote_rescue_hidden(x), do: x
      try do
        raise "matrix"
      rescue
        _ ->
        defmacro src_defmacro_x_use_in_quote_rescue_snoc(q), do: quote(do: {unquote(q)})
        defmacro src_defmacro_x_use_in_quote_rescue_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
      end
    end
  end

  def target_marker, do: :ok
end
