# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInReceive do
  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    use Src.Defmacro.XUseInReceive.Injector
  end

  def local_site(a, b), do: src_defmacro_x_use_in_receive_snoc(a, b) # @local
end
