# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInCase do
  def local_forward(a, b), do: src_defp_x_use_in_case_snoc(a, b) # @local_forward

  case Code.ensure_loaded?(Kernel) do
    _ ->
    use Src.Defp.XUseInCase.Injector
  end

  def local_site(a, b), do: src_defp_x_use_in_case_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_use_in_case_snoc(a), # @uses_0
      a,
      b
    }
  end
end
