# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XReceive do
  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    defdelegate src_defdelegate_unresolvable_x_receive_snoc(q, x), to: Src.DefdelegateUnresolvable.XReceive.Missing
  end

  def local_site(a, b), do: src_defdelegate_unresolvable_x_receive_snoc(a, b) # @local
end
