# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFrom.XUnless do
  require EEx

  def local_forward(a, b), do: src_eex_function_from_x_unless_snoc(a, b) # @local_forward

  unless Code.ensure_loaded?(Matrix.Absent) do
    EEx.function_from_string(:def, :src_eex_function_from_x_unless_snoc, "<%= inspect({q, x}) %>", [:q, :x])
  end

  def local_site(a, b), do: src_eex_function_from_x_unless_snoc(a, b) # @local
end
