# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInjectedParens.Injector do
  defmacro(__using__(_), do: quote(do: (
    use(Src.Defp.XUseInjectedParens.Inner)
    import(Src.Defp.XUseInjectedParens.Helpers, warn: false)
    defp(src_defp_x_use_injected_parens_hidden(x), do: x)
    defp(src_defp_x_use_injected_parens_snoc(q), do: {q})
    defp(src_defp_x_use_injected_parens_snoc(q, x), do: {q, x})
  )))

  def target_marker, do: :ok
end
