# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInjectedDefaults do
  use Src.Defp.XUseInjectedDefaults.Injector

  def local_site(a, b), do: src_defp_x_use_injected_defaults_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_use_injected_defaults_snoc(), # @uses_0
      src_defp_x_use_injected_defaults_snoc(a), # @uses_1
      a,
      b
    }
  end
end
