# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseInQuoteTry.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacrop.XUseInQuoteTry.Inner
      import Src.Defmacrop.XUseInQuoteTry.Helpers, warn: false
      defp src_defmacrop_x_use_in_quote_try_hidden(x), do: x
      try do
        defmacrop src_defmacrop_x_use_in_quote_try_snoc(q), do: quote(do: {unquote(q)})
        defmacrop src_defmacrop_x_use_in_quote_try_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
      rescue
        _ -> nil
      end
    end
  end

  def target_marker, do: :ok
end
