# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInQuoteReceive.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Def.XUseInQuoteReceive.Inner
      import Src.Def.XUseInQuoteReceive.Helpers, warn: false
      defp src_def_x_use_in_quote_receive_hidden(x), do: x
      receive do
        :matrix_never_sent -> nil
      after
        0 ->
        def src_def_x_use_in_quote_receive_snoc(q), do: {q}
        def src_def_x_use_in_quote_receive_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
