# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInjectedParens.DefUsing do
  def(__using__(_), do: quote(do:
    def(src_defmacro_x_use_injected_parens_not_injected(x), do: x)
  ))

  def target_marker, do: :ok
end
