# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguardp.XReceive do
  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    defguardp src_defguardp_x_receive_snoc(q, x) when is_list(q) or is_list(x)
  end

  def local_site(a, b), do: src_defguardp_x_receive_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
