# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInQuoteFor.Other do
  use Src.Defguard.XUseInQuoteFor.Injector
end
