# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XReceive.Target do
  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    def src_defdelegate_x_receive_snoc(q, x), do: {q, x}
  end

  def target_marker, do: :ok
end
