# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XSpecParensSpace do
  @spec (src_defdelegate_x_spec_parens_space_snoc(term(), term()) :: term()) # @spec_2
  defdelegate src_defdelegate_x_spec_parens_space_snoc(q, x), to: Src.Defdelegate.XSpecParensSpace.Target

  def local_site(a, b), do: src_defdelegate_x_spec_parens_space_snoc(a, b) # @local
end
