# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XRescue.Target do
  try do
    raise "matrix"
  rescue
    _ ->
    def src_defdelegate_x_rescue_snoc(q, x), do: {q, x}
  end

  def target_marker, do: :ok
end
