# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInWith.Other do
  with true <- Code.ensure_loaded?(Kernel) do
    use Src.Defguard.XUseInWith.Injector
  end
end
