# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XTryAfter do
  try do
    nil
  after
    defmacro src_defmacro_x_try_after_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  end

  def local_site(a, b), do: src_defmacro_x_try_after_snoc(a, b) # @local
end
