# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInQuoteReceive.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defp.XUseInQuoteReceive.Inner
      import Src.Defp.XUseInQuoteReceive.Helpers, warn: false
      defp src_defp_x_use_in_quote_receive_hidden(x), do: x
      receive do
        :matrix_never_sent -> nil
      after
        0 ->
        defp src_defp_x_use_in_quote_receive_snoc(q), do: {q}
        defp src_defp_x_use_in_quote_receive_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
