# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInTry.Other do
  try do
    use Src.Defmacro.XUseInTry.Injector
  rescue
    _ -> nil
  end
end
