# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInQuoteConditional.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defp.XUseInQuoteConditional.Inner
      import Src.Defp.XUseInQuoteConditional.Helpers, warn: false
      defp src_defp_x_use_in_quote_conditional_hidden(x), do: x
      if Code.ensure_loaded?(Kernel) do
        defp src_defp_x_use_in_quote_conditional_snoc(q), do: {q}
        defp src_defp_x_use_in_quote_conditional_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
