# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInFor do
  @limit 5 # @before_for
  for x <- [6], do: @limit x # @in_for
  def read, do: @limit # @read
end
