# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseQuoteLocationKeep.Inner do
  defmacro __using__(_) do
    quote do
      def src_defguard_x_use_quote_location_keep_chained(x), do: x
    end
  end

  def target_marker, do: :ok
end
