# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInQuoteFor do
  use Src.Defguard.XUseInQuoteFor.Injector

  def local_site(a, b), do: src_defguard_x_use_in_quote_for_snoc(a, b) # @local
end
