# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInFor.Other do
  for _ <- [:once] do
    use Src.Defmacro.XUseInFor.Injector
  end
end
