# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInElseList do
  @limit 12 # @before_if
  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: [
    @limit 13 # @in_else
  ]
  def read, do: @limit # @read
end
