# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XModuledocIf do
  if Code.ensure_loaded?(Kernel) do
    @moduledoc "The documented module."
  end

  def src_def_x_moduledoc_if_snoc(q, x), do: {q, x}

  def local_site(a, b), do: src_def_x_moduledoc_if_snoc(a, b) # @local

  def module_local, do: Src.Def.XModuledocIf # @module_local
end
