# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.SrcStaleBeam do
  def local_forward(a, b), do: src_def_src_stale_beam_snoc(a, b) # @local_forward

  @spec src_def_src_stale_beam_snoc(term(), term()) :: term() # @spec_2
  def src_def_src_stale_beam_snoc(q, x), do: {q, x}

  def local_site(a, b), do: src_def_src_stale_beam_snoc(a, b) # @local
end
