# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defprotocol Src.Def.XModuledocProtocol do
  @moduledoc "The documented protocol."

  def src_def_x_moduledoc_protocol_snoc(q, x)
end
