# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguardp.XTryAfter do
  try do
    nil
  after
    defguardp src_defguardp_x_try_after_snoc(q, x) when is_list(q) or is_list(x)
  end

  def local_site(a, b), do: src_defguardp_x_try_after_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
