# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XIfElse do
  if Code.ensure_loaded?(Kernel) do
    def src_def_x_if_else_snoc(q, x \\ nil), do: {q, x}
  else
    def src_def_x_if_else_snoc(q), do: {q} # @not_compiled
  end

  def local_site(a, b), do: src_def_x_if_else_snoc(a, b) # @local
end
