# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInReceive do
  def local_forward(a, b), do: src_defp_x_use_in_receive_snoc(a, b) # @local_forward

  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    use Src.Defp.XUseInReceive.Injector
  end

  def local_site(a, b), do: src_defp_x_use_in_receive_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_use_in_receive_snoc(a), # @uses_0
      a,
      b
    }
  end
end
