# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XCase do
  def local_forward(a, b), do: src_defdelegate_unresolvable_x_case_snoc(a, b) # @local_forward

  case Code.ensure_loaded?(Kernel) do
    _ ->
    defdelegate src_defdelegate_unresolvable_x_case_snoc(q, x), to: Src.DefdelegateUnresolvable.XCase.Missing
  end

  def local_site(a, b), do: src_defdelegate_unresolvable_x_case_snoc(a, b) # @local
end
