# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XWith do
  with true <- Code.ensure_loaded?(Kernel) do
    defdelegate src_defdelegate_compiled_x_with_snoc(q, x), to: Src.DefdelegateCompiled.XWith.Target
  end

  def local_site(a, b), do: src_defdelegate_compiled_x_with_snoc(a, b) # @local
end
