# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInjectedDefaults.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacro.XUseInjectedDefaults.Inner
      import Src.Defmacro.XUseInjectedDefaults.Helpers, warn: false
      defp src_defmacro_x_use_injected_defaults_hidden(x), do: x
      defmacro src_defmacro_x_use_injected_defaults_snoc(a \\ nil, b \\ nil)
      defmacro src_defmacro_x_use_injected_defaults_snoc(a, b) when is_nil(a), do: quote(do: {unquote(a), unquote(b)})
      defmacro src_defmacro_x_use_injected_defaults_snoc(a, b), do: quote(do: {unquote(a), unquote(b)})
    end
  end

  def target_marker, do: :ok
end
