# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseQuoteDoBlock.Injector do
  defmacro __using__(_) do
    quote do: (
      use Src.Defguard.XUseQuoteDoBlock.Inner
      import Src.Defguard.XUseQuoteDoBlock.Helpers, warn: false
      defp src_defguard_x_use_quote_do_block_hidden(x), do: x
      defguard src_defguard_x_use_quote_do_block_snoc(q) when is_list(q)
      defguard src_defguard_x_use_quote_do_block_snoc(q, x) when is_list(q) or is_list(x)
    )
  end

  def target_marker, do: :ok
end
