# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseQuoteDoBlock.Injector do
  defmacro __using__(_) do
    quote do: (
      use Src.Def.XUseQuoteDoBlock.Inner
      import Src.Def.XUseQuoteDoBlock.Helpers, warn: false
      defp src_def_x_use_quote_do_block_hidden(x), do: x
      def src_def_x_use_quote_do_block_snoc(q), do: {q}
      def src_def_x_use_quote_do_block_snoc(q, x), do: {q, x}
    )
  end

  def target_marker, do: :ok
end
