# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFrom.XFor do
  require EEx

  def local_forward(a, b), do: src_eex_function_from_x_for_snoc(a, b) # @local_forward

  for _ <- [:once] do
    EEx.function_from_string(:def, :src_eex_function_from_x_for_snoc, "<%= inspect({q, x}) %>", [:q, :x])
  end

  def local_site(a, b), do: src_eex_function_from_x_for_snoc(a, b) # @local
end
