# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInQuoteCase.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Def.XUseInQuoteCase.Inner
      import Src.Def.XUseInQuoteCase.Helpers, warn: false
      defp src_def_x_use_in_quote_case_hidden(x), do: x
      case Code.ensure_loaded?(Kernel) do
        _ ->
        def src_def_x_use_in_quote_case_snoc(q), do: {q}
        def src_def_x_use_in_quote_case_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
