# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseQuoteQuotedDo.Injector do
  defmacro __using__(_) do
    quote "do": (
      use Src.Defp.XUseQuoteQuotedDo.Inner
      import Src.Defp.XUseQuoteQuotedDo.Helpers, warn: false
      defp src_defp_x_use_quote_quoted_do_hidden(x), do: x
      defp src_defp_x_use_quote_quoted_do_snoc(q), do: {q}
      defp src_defp_x_use_quote_quoted_do_snoc(q, x), do: {q, x}
    )
  end

  def target_marker, do: :ok
end
