# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Variable.XInterpVarForCall do
  for x <- [1] do # @binding
    IO.puts("#{x}") # @interpolation
  end
end
