# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInQuoteRescue do
  use Src.Def.XUseInQuoteRescue.Injector

  def local_site(a, b), do: src_def_x_use_in_quote_rescue_snoc(a, b) # @local
end
