# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInjected do
  use Src.Defguard.XUseInjected.Injector

  def local_site(a, b), do: src_defguard_x_use_injected_snoc(a, b) # @local
end
