# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseInQuoteElseList.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacrop.XUseInQuoteElseList.Inner
      import Src.Defmacrop.XUseInQuoteElseList.Helpers, warn: false
      defp src_defmacrop_x_use_in_quote_else_list_hidden(x), do: x
      if Code.ensure_loaded?(Matrix.Absent), do: nil, else: [
        defmacrop(src_defmacrop_x_use_in_quote_else_list_snoc(q), do: quote(do: {unquote(q)})),
        defmacrop(src_defmacrop_x_use_in_quote_else_list_snoc(q, x), do: quote(do: {unquote(q), unquote(x)}))
      ]
    end
  end

  def target_marker, do: :ok
end
