# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInjectedDefaults do
  use Src.Defmacro.XUseInjectedDefaults.Injector

  def local_site(a, b), do: src_defmacro_x_use_injected_defaults_snoc(a, b) # @local
end
