# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInElseQuoted.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defp.XUseInElseQuoted.Inner
      import Src.Defp.XUseInElseQuoted.Helpers, warn: false
      defp src_defp_x_use_in_else_quoted_hidden(x), do: x
      defp src_defp_x_use_in_else_quoted_snoc(q), do: {q}
      defp src_defp_x_use_in_else_quoted_snoc(q, x), do: {q, x}
    end
  end

  def target_marker, do: :ok
end
