# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XRescue do
  def local_forward(a, b), do: src_defdelegate_compiled_x_rescue_snoc(a, b) # @local_forward

  try do
    raise "matrix"
  rescue
    _ ->
    defdelegate src_defdelegate_compiled_x_rescue_snoc(q, x), to: Src.DefdelegateCompiled.XRescue.Target
  end

  def local_site(a, b), do: src_defdelegate_compiled_x_rescue_snoc(a, b) # @local
end
