# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XElseKeyword do
  def local_forward(a, b), do: src_defdelegate_unresolvable_x_else_keyword_snoc(a, b) # @local_forward

  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: (
    defdelegate src_defdelegate_unresolvable_x_else_keyword_snoc(q, x), to: Src.DefdelegateUnresolvable.XElseKeyword.Missing
  )

  def local_site(a, b), do: src_defdelegate_unresolvable_x_else_keyword_snoc(a, b) # @local
end
