# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInCase do
  case Code.ensure_loaded?(Kernel) do
    _ ->
    use Src.Defmacro.XUseInCase.Injector
  end

  def local_site(a, b), do: src_defmacro_x_use_in_case_snoc(a, b) # @local
end
