# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInElseQuoted.Other do
  if Code.ensure_loaded?(Matrix.Absent), do: nil, "else": (
    use Src.Defmacro.XUseInElseQuoted.Injector
  )
end
