# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInjectedParens.Injector do
  defmacro(__using__(_), do: quote(unquote: false, do: (
    use(Src.Defmacro.XUseInjectedParens.Inner)
    import(Src.Defmacro.XUseInjectedParens.Helpers, warn: false)
    defp(src_defmacro_x_use_injected_parens_hidden(x), do: x)
    defmacro(src_defmacro_x_use_injected_parens_snoc(q), do: quote(do: {unquote(q)}))
    defmacro(src_defmacro_x_use_injected_parens_snoc(q, x), do: quote(do: {unquote(q), unquote(x)}))
  )))

  def target_marker, do: :ok
end
