# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XElseKeyword do
  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: (
    defmacrop src_defmacrop_x_else_keyword_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  )

  def local_site(a, b), do: src_defmacrop_x_else_keyword_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
