# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInQuoteElseQuoted.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacro.XUseInQuoteElseQuoted.Inner
      import Src.Defmacro.XUseInQuoteElseQuoted.Helpers, warn: false
      defp src_defmacro_x_use_in_quote_else_quoted_hidden(x), do: x
      if Code.ensure_loaded?(Matrix.Absent), do: nil, "else": (
        defmacro src_defmacro_x_use_in_quote_else_quoted_snoc(q), do: quote(do: {unquote(q)})
        defmacro src_defmacro_x_use_in_quote_else_quoted_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
      )
    end
  end

  def target_marker, do: :ok
end
