# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseQuoteLocationKeep do
  use Src.Defp.XUseQuoteLocationKeep.Injector

  def local_site(a, b), do: src_defp_x_use_quote_location_keep_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_use_quote_location_keep_snoc(a), # @uses_0
      a,
      b
    }
  end
end
