# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInTry do
  try do
    :ok
    @limit 7 # @in_try
  rescue
    _ -> @limit 8 # @in_rescue
  end
  def read, do: @limit # @read
end
