# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInCond do
  cond do
    Code.ensure_loaded?(Kernel) ->
    use Src.Defmacro.XUseInCond.Injector
  end

  def local_site(a, b), do: src_defmacro_x_use_in_cond_snoc(a, b) # @local
end
