# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XIfElse do
  if Code.ensure_loaded?(Kernel) do
    defp src_defp_x_if_else_snoc(q, x \\ nil), do: {q, x}
  else
    defp src_defp_x_if_else_snoc(q), do: {q} # @not_compiled
  end

  def local_site(a, b), do: src_defp_x_if_else_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_if_else_snoc(a), # @uses_0
      a,
      b
    }
  end
end
