# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInTryAfter do
  def local_forward(a, b), do: src_def_x_use_in_try_after_snoc(a, b) # @local_forward

  try do
    nil
  after
    use Src.Def.XUseInTryAfter.Injector
  end

  def local_site(a, b), do: src_def_x_use_in_try_after_snoc(a, b) # @local
end
