# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XTryAfter.Target do
  try do
    nil
  after
    def src_defdelegate_x_try_after_snoc(q, x), do: {q, x}
  end

  def target_marker, do: :ok
end
