# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInQuoteUnless.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defp.XUseInQuoteUnless.Inner
      import Src.Defp.XUseInQuoteUnless.Helpers, warn: false
      defp src_defp_x_use_in_quote_unless_hidden(x), do: x
      unless Code.ensure_loaded?(Matrix.Absent) do
        defp src_defp_x_use_in_quote_unless_snoc(q), do: {q}
        defp src_defp_x_use_in_quote_unless_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
