# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XRescue do
  def local_forward(a, b), do: src_defp_x_rescue_snoc(a, b) # @local_forward

  try do
    raise "matrix"
  rescue
    _ ->
    defp src_defp_x_rescue_snoc(q, x), do: {q, x}
  end

  def local_site(a, b), do: src_defp_x_rescue_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
