# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XModuledoc do
  @moduledoc "The documented module."

  def src_def_x_moduledoc_snoc(q, x), do: {q, x}

  def local_site(a, b), do: src_def_x_moduledoc_snoc(a, b) # @local

  def module_local, do: Src.Def.XModuledoc # @module_local
end
