# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInElseList.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Def.XUseInElseList.Inner
      import Src.Def.XUseInElseList.Helpers, warn: false
      defp src_def_x_use_in_else_list_hidden(x), do: x
      def src_def_x_use_in_else_list_snoc(q), do: {q}
      def src_def_x_use_in_else_list_snoc(q, x), do: {q, x}
    end
  end

  def target_marker, do: :ok
end
