# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInTryAfter do
  @limit 14 # @before_try
  try do
    :ok
  after
    @limit 15 # @in_after
  end
  def read, do: @limit # @read
end
