# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XElseList do
  def local_forward(a, b), do: src_defp_x_else_list_snoc(a, b) # @local_forward

  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: [
    defp(src_defp_x_else_list_snoc(q, x), do: {q, x})
  ]

  def local_site(a, b), do: src_defp_x_else_list_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
