# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseQuoteDoBlock.Injector do
  defmacro __using__(_) do
    quote do: (
      use Src.Defmacro.XUseQuoteDoBlock.Inner
      import Src.Defmacro.XUseQuoteDoBlock.Helpers, warn: false
      defp src_defmacro_x_use_quote_do_block_hidden(x), do: x
      defmacro src_defmacro_x_use_quote_do_block_snoc(q), do: quote(do: {unquote(q)})
      defmacro src_defmacro_x_use_quote_do_block_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
    ), unquote: false
  end

  def target_marker, do: :ok
end
