# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Variable.XInterpVarForTest do
  use ExUnit.Case

  for x <- [1] do # @binding
    test "handles #{x}" do # @interpolation
      assert unquote(x) # @body
    end
  end
end
