# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseInjectedDefaults.PrivateUsing do
  defmacrop __using__(_) do
    quote do
      def src_defmacrop_x_use_injected_defaults_privately_injected(x), do: x
    end
  end

  def target_marker, do: :ok
end
