# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XParensGuarded do
  def local_forward(a, b), do: src_defp_x_parens_guarded_snoc(a, b) # @local_forward

  defp(src_defp_x_parens_guarded_snoc(q, x) when is_tuple(q), do: {q, x})

  def local_site(a, b), do: src_defp_x_parens_guarded_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
