# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateAsAttribute.SrcStaleBeam.Target do
  def delegated_src_defdelegate_as_attribute_src_stale_beam_snoc(q, x), do: {q, x}

  def target_marker, do: :ok
end
