# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInQuoteCond.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacro.XUseInQuoteCond.Inner
      import Src.Defmacro.XUseInQuoteCond.Helpers, warn: false
      defp src_defmacro_x_use_in_quote_cond_hidden(x), do: x
      cond do
        Code.ensure_loaded?(Kernel) ->
        defmacro src_defmacro_x_use_in_quote_cond_snoc(q), do: quote(do: {unquote(q)})
        defmacro src_defmacro_x_use_in_quote_cond_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
      end
    end
  end

  def target_marker, do: :ok
end
