# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInElseList do
  def local_forward(a, b), do: src_def_x_use_in_else_list_snoc(a, b) # @local_forward

  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: [
    use Src.Def.XUseInElseList.Injector
  ]

  def local_site(a, b), do: src_def_x_use_in_else_list_snoc(a, b) # @local
end
