# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInQuoteWith.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defguard.XUseInQuoteWith.Inner
      import Src.Defguard.XUseInQuoteWith.Helpers, warn: false
      defp src_defguard_x_use_in_quote_with_hidden(x), do: x
      with true <- Code.ensure_loaded?(Kernel) do
        defguard src_defguard_x_use_in_quote_with_snoc(q) when is_list(q)
        defguard src_defguard_x_use_in_quote_with_snoc(q, x) when is_list(q) or is_list(x)
      end
    end
  end

  def target_marker, do: :ok
end
