# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInCase do
  case Code.ensure_loaded?(Kernel) do
    true -> @limit 3 # @in_true
    _ -> @limit 4 # @in_other
  end
  def read, do: @limit # @read
end
