# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInTry do
  try do
    use Src.Defmacro.XUseInTry.Injector
  rescue
    _ -> nil
  end

  def local_site(a, b), do: src_defmacro_x_use_in_try_snoc(a, b) # @local
end
