# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInElseKeyword.PrivateUsing do
  defmacrop __using__(_) do
    quote do
      def src_defmacro_x_use_in_else_keyword_privately_injected(x), do: x
    end
  end

  def target_marker, do: :ok
end
