# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInCond.Other do
  cond do
    Code.ensure_loaded?(Kernel) ->
    use Src.Def.XUseInCond.Injector
  end
end
