# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseQuoteQuotedDo.Injector do
  defmacro __using__(_) do
    quote "do": (
      use Src.Defmacrop.XUseQuoteQuotedDo.Inner
      import Src.Defmacrop.XUseQuoteQuotedDo.Helpers, warn: false
      defp src_defmacrop_x_use_quote_quoted_do_hidden(x), do: x
      defmacrop src_defmacrop_x_use_quote_quoted_do_snoc(q), do: quote(do: {unquote(q)})
      defmacrop src_defmacrop_x_use_quote_quoted_do_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
    ), unquote: false
  end

  def target_marker, do: :ok
end
