# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInQuoteReceive.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defguard.XUseInQuoteReceive.Inner
      import Src.Defguard.XUseInQuoteReceive.Helpers, warn: false
      defp src_defguard_x_use_in_quote_receive_hidden(x), do: x
      receive do
        :matrix_never_sent -> nil
      after
        0 ->
        defguard src_defguard_x_use_in_quote_receive_snoc(q) when is_list(q)
        defguard src_defguard_x_use_in_quote_receive_snoc(q, x) when is_list(q) or is_list(x)
      end
    end
  end

  def target_marker, do: :ok
end
