# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFromArgs.XArityZero do
  require EEx

  @args []
  EEx.function_from_string(:def, :src_eex_function_from_args_x_arity_zero_snoc, "<%= inspect({}) %>", @args)
  @args [:q, :x]
  EEx.function_from_string(:def, :src_eex_function_from_args_x_arity_zero_snoc, "<%= inspect({q, x}) %>", @args)

  def local_site(a, b), do: src_eex_function_from_args_x_arity_zero_snoc(a, b) # @local
end
