# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseInQuoteTryAfter.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacrop.XUseInQuoteTryAfter.Inner
      import Src.Defmacrop.XUseInQuoteTryAfter.Helpers, warn: false
      defp src_defmacrop_x_use_in_quote_try_after_hidden(x), do: x
      try do
        nil
      after
        defmacrop src_defmacrop_x_use_in_quote_try_after_snoc(q), do: quote(do: {unquote(q)})
        defmacrop src_defmacrop_x_use_in_quote_try_after_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
      end
    end
  end

  def target_marker, do: :ok
end
