# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XCatch do
  try do
    throw :matrix
  catch
    _ ->
    defmacro src_defmacro_x_catch_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  end

  def local_site(a, b), do: src_defmacro_x_catch_snoc(a, b) # @local
end
