# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInjectedParens do
  use Src.Defguard.XUseInjectedParens.Injector

  def local_site(a, b), do: src_defguard_x_use_injected_parens_snoc(a, b) # @local
end
