# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInRescue do
  def local_forward(a, b), do: src_def_x_use_in_rescue_snoc(a, b) # @local_forward

  try do
    raise "matrix"
  rescue
    _ ->
    use Src.Def.XUseInRescue.Injector
  end

  def local_site(a, b), do: src_def_x_use_in_rescue_snoc(a, b) # @local
end
