# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseQuoteLocationKeep do
  use Src.Def.XUseQuoteLocationKeep.Injector

  def local_site(a, b), do: src_def_x_use_quote_location_keep_snoc(a, b) # @local
end
