# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Variable.XGuardVarFnParens do
  def run do
    y = 1 # @binding
    fn(x when x > y) -> y end # @guard @body
  end
end
