# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XReceive do
  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    defp src_defp_x_receive_snoc(q, x), do: {q, x}
  end

  def local_site(a, b), do: src_defp_x_receive_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
