# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XElseList do
  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: [
    defguard(src_defguard_x_else_list_snoc(q, x) when is_list(q) or is_list(x))
  ]

  def local_site(a, b), do: src_defguard_x_else_list_snoc(a, b) # @local
end
