# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInQuoteElseKeyword.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defp.XUseInQuoteElseKeyword.Inner
      import Src.Defp.XUseInQuoteElseKeyword.Helpers, warn: false
      defp src_defp_x_use_in_quote_else_keyword_hidden(x), do: x
      if Code.ensure_loaded?(Matrix.Absent), do: nil, else: (
        defp src_defp_x_use_in_quote_else_keyword_snoc(q), do: {q}
        defp src_defp_x_use_in_quote_else_keyword_snoc(q, x), do: {q, x}
      )
    end
  end

  def target_marker, do: :ok
end
