# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XIfElse do
  if Code.ensure_loaded?(Kernel) do
    defmacro src_defmacro_x_if_else_snoc(q, x \\ nil), do: quote(do: {unquote(q), unquote(x)})
  else
    defmacro src_defmacro_x_if_else_snoc(q), do: quote(do: {unquote(q)}) # @not_compiled
  end

  def local_site(a, b), do: src_defmacro_x_if_else_snoc(a, b) # @local
end
