# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInjected.Helpers do
  def src_defguard_x_use_injected_helper(x), do: x

  def target_marker, do: :ok
end
