# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XParensGuarded do
  defmacro(src_defmacro_x_parens_guarded_snoc(q, x) when is_tuple(q), do: quote(do: {unquote(q), unquote(x)}))

  def local_site(a, b), do: src_defmacro_x_parens_guarded_snoc(a, b) # @local
end
