# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseQuoteLocationKeep.Injector do
  defmacro __using__(_) do
    quote(unquote: false, location: :keep, do: (
      use Src.Defmacrop.XUseQuoteLocationKeep.Inner
      import Src.Defmacrop.XUseQuoteLocationKeep.Helpers, warn: false
      defp src_defmacrop_x_use_quote_location_keep_hidden(x), do: x
      defmacrop src_defmacrop_x_use_quote_location_keep_snoc(q), do: quote(do: {unquote(q)})
      defmacrop src_defmacrop_x_use_quote_location_keep_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
    ))
  end

  def target_marker, do: :ok
end
