# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInReceive.Other do
  receive do
    :matrix_never_sent -> nil
  after
    0 ->
    use Src.Def.XUseInReceive.Injector
  end
end
