# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInCatch do
  @limit 18 # @before_try
  try do
    throw :matrix
  catch
    _ -> @limit 19 # @in_catch
  end
  def read, do: @limit # @read
end
