# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XSpecParensSpace do
  @spec (src_def_x_spec_parens_space_snoc(term(), term()) :: term()) # @spec_2
  def src_def_x_spec_parens_space_snoc(q, x), do: {q, x}

  def local_site(a, b), do: src_def_x_spec_parens_space_snoc(a, b) # @local
end
