# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInElseKeyword do
  if Code.ensure_loaded?(Matrix.Absent), do: nil, else: (
    use Src.Defmacro.XUseInElseKeyword.Injector
  )

  def local_site(a, b), do: src_defmacro_x_use_in_else_keyword_snoc(a, b) # @local
end
