# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseInQuoteCase.Injector do
  defmacro __using__(_) do
    quote unquote: false do
      use Src.Defmacrop.XUseInQuoteCase.Inner
      import Src.Defmacrop.XUseInQuoteCase.Helpers, warn: false
      defp src_defmacrop_x_use_in_quote_case_hidden(x), do: x
      case Code.ensure_loaded?(Kernel) do
        _ ->
        defmacrop src_defmacrop_x_use_in_quote_case_snoc(q), do: quote(do: {unquote(q)})
        defmacrop src_defmacrop_x_use_in_quote_case_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
      end
    end
  end

  def target_marker, do: :ok
end
