# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInWith do
  with true <- Code.ensure_loaded?(Kernel) do
    use Src.Defmacro.XUseInWith.Injector
  end

  def local_site(a, b), do: src_defmacro_x_use_in_with_snoc(a, b) # @local
end
