# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInQuoteFor.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defp.XUseInQuoteFor.Inner
      import Src.Defp.XUseInQuoteFor.Helpers, warn: false
      defp src_defp_x_use_in_quote_for_hidden(x), do: x
      for _ <- [:once] do
        defp src_defp_x_use_in_quote_for_snoc(q), do: {q}
        defp src_defp_x_use_in_quote_for_snoc(q, x), do: {q, x}
      end
    end
  end

  def target_marker, do: :ok
end
