# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInElseQuoted do
  def local_forward(a, b), do: src_defp_x_use_in_else_quoted_snoc(a, b) # @local_forward

  if Code.ensure_loaded?(Matrix.Absent), do: nil, "else": (
    use Src.Defp.XUseInElseQuoted.Injector
  )

  def local_site(a, b), do: src_defp_x_use_in_else_quoted_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_use_in_else_quoted_snoc(a), # @uses_0
      a,
      b
    }
  end
end
