# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateList.SrcStaleBeam do
  defdelegate src_defdelegate_list_src_stale_beam_snoc(q, x), [to: Src.DefdelegateList.SrcStaleBeam.Target]

  def local_site(a, b), do: src_defdelegate_list_src_stale_beam_snoc(a, b) # @local
end
