# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInRescue do
  @limit 16 # @before_try
  try do
    raise "matrix"
  rescue
    _ -> @limit 17 # @in_rescue
  end
  def read, do: @limit # @read
end
