# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Attribute.XAttributeInWith do
  @limit 9 # @before_with
  with true <- Code.ensure_loaded?(Kernel), do: @limit 10 # @in_with
  def read, do: @limit # @read
end
