# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseInCatch.Other do
  try do
    throw :matrix
  catch
    _ ->
    use Src.Defmacro.XUseInCatch.Injector
  end
end
