# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateImports.SrcStaleBeam.Target do
  import Src.DefdelegateImports.SrcStaleBeam.Source, only: [src_defdelegate_imports_src_stale_beam_snoc: 2], warn: false



  def target_marker, do: :ok
end
