# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XUseQuoteDoBlock do
  use Src.Defmacro.XUseQuoteDoBlock.Injector

  def local_site(a, b), do: src_defmacro_x_use_quote_do_block_snoc(a, b) # @local
end
