# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseInUnless do
  def local_forward(a, b), do: src_defp_x_use_in_unless_snoc(a, b) # @local_forward

  unless Code.ensure_loaded?(Matrix.Absent) do
    use Src.Defp.XUseInUnless.Injector
  end

  def local_site(a, b), do: src_defp_x_use_in_unless_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_use_in_unless_snoc(a), # @uses_0
      a,
      b
    }
  end
end
