# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XCatch do
  def local_forward(a, b), do: src_defdelegate_x_catch_snoc(a, b) # @local_forward

  try do
    throw :matrix
  catch
    _ ->
    defdelegate src_defdelegate_x_catch_snoc(q, x), to: Src.Defdelegate.XCatch.Target
  end

  def local_site(a, b), do: src_defdelegate_x_catch_snoc(a, b) # @local
end
