# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XUseApply.Injector do
  defmacro __using__(which) when is_atom(which), do: apply(__MODULE__, which, [])

  def view do
    quote unquote: false do
      defmacrop src_defmacrop_x_use_apply_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
    end
  end

  defp secret do
    quote do
      def src_defmacrop_x_use_apply_secret(x), do: x
    end
  end

  def target_marker, do: :ok
end
