# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Variable.XGuardVarFor do
  def run(list) do
    y = 1 # @binding
    for x when x > y <- list, do: y # @guard @body
  end
end
