# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFromArgs.XNotACall do
  require EEx

  @args [:q, :x]
  EEx.function_from_string(:def, :src_eex_function_from_args_x_not_a_call_snoc, "<%= inspect({q, x}) %>", @args)

  def local_site(a, b), do: src_eex_function_from_args_x_not_a_call_snoc(a, b) # @local
end
