# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInQuoteElseList.Injector do
  defmacro __using__(_) do
    quote do
      use Src.Defguard.XUseInQuoteElseList.Inner
      import Src.Defguard.XUseInQuoteElseList.Helpers, warn: false
      defp src_defguard_x_use_in_quote_else_list_hidden(x), do: x
      if Code.ensure_loaded?(Matrix.Absent), do: nil, else: [
        defguard(src_defguard_x_use_in_quote_else_list_snoc(q) when is_list(q)),
        defguard(src_defguard_x_use_in_quote_else_list_snoc(q, x) when is_list(q) or is_list(x))
      ]
    end
  end

  def target_marker, do: :ok
end
