# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInCatch do
  try do
    throw :matrix
  catch
    _ ->
    use Src.Defguard.XUseInCatch.Injector
  end

  def local_site(a, b), do: src_defguard_x_use_in_catch_snoc(a, b) # @local
end
