# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguard.XUseInUnless.Other do
  unless Code.ensure_loaded?(Matrix.Absent) do
    use Src.Defguard.XUseInUnless.Injector
  end
end
