# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XUseQuoteLocationKeep.Injector do
  defmacro __using__(_) do
    quote(location: :keep, do: (
      use Src.Defp.XUseQuoteLocationKeep.Inner
      import Src.Defp.XUseQuoteLocationKeep.Helpers, warn: false
      defp src_defp_x_use_quote_location_keep_hidden(x), do: x
      defp src_defp_x_use_quote_location_keep_snoc(q), do: {q}
      defp src_defp_x_use_quote_location_keep_snoc(q, x), do: {q, x}
    ))
  end

  def target_marker, do: :ok
end
