# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFrom.SrcStaleBeam do
  require EEx

  def local_forward(a, b), do: src_eex_function_from_src_stale_beam_snoc(a, b) # @local_forward

  @spec src_eex_function_from_src_stale_beam_snoc(term(), term()) :: term() # @spec_2
  EEx.function_from_string(:def, :src_eex_function_from_src_stale_beam_snoc, "<%= inspect({q, x}) %>", [:q, :x])

  def local_site(a, b), do: src_eex_function_from_src_stale_beam_snoc(a, b) # @local
end
