# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUseInCatch do
  def local_forward(a, b), do: src_def_x_use_in_catch_snoc(a, b) # @local_forward

  try do
    throw :matrix
  catch
    _ ->
    use Src.Def.XUseInCatch.Injector
  end

  def local_site(a, b), do: src_def_x_use_in_catch_snoc(a, b) # @local
end
