package org.elixir_lang.beam.decompiler

import com.intellij.psi.tree.TokenSet
import org.elixir_lang.ElixirLexer
import org.elixir_lang.beam.chunk.DebugInfo
import org.elixir_lang.beam.chunk.beam_documentation.Docs
import org.elixir_lang.beam.chunk.beam_documentation.Documentation
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.V1
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.Definition
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.definition.Clause
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.definition.DefaultArgumentClause
import org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.AbstractCodeCompileOptions
import org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function
import org.elixir_lang.psi.ElixirTypes
import org.elixir_lang.psi.call.name.Function.DEF
import org.elixir_lang.psi.call.name.Function.DEFP

/**
 * Where a definition's decompiled clauses come from. The decompiler and the stub builder both choose through
 * [clauseSource].
 */
sealed interface ClauseSource {
    /** Parameters of the first clause. */
    val parameters: List<String>
    val isAutoGeneratedName: Boolean

    class ErlangAbstractCode(val function: Function) : ClauseSource {
        override val parameters: List<String> get() = function.clauses.firstOrNull()?.parameters.orEmpty()
        override val isAutoGeneratedName: Boolean = false
    }

    class ElixirDebugInfo(val definition: Definition, private val clauses: List<Clause>) : ClauseSource {
        override val parameters: List<String> get() = clauses.first().parameters
        override val isAutoGeneratedName: Boolean get() = clauses.first().isAutoGeneratedName
    }

    class DocsSignatures(val signatures: List<String>) : ClauseSource {
        override val parameters: List<String> get() = signatureParameters(signatures.first().replace("\r", ""))

        // Elixir names a pattern argument in a docs signature after its shape (`map`, `list`, ...), so no name
        // here is known to be from source.
        override val isAutoGeneratedName: Boolean = true
    }

    /** An arity with no `Docs` entry of its own, named from the signature of the entry whose defaults cover it. */
    class CoveringDocsSignature(override val parameters: List<String>) : ClauseSource {
        override val isAutoGeneratedName: Boolean = true
    }

    class Generated(
        val decompiler: MacroNameArity,
        private val macroNameArity: org.elixir_lang.beam.MacroNameArity
    ) : ClauseSource {
        override val parameters: List<String> get() = decompiler.parameters(macroNameArity).toList()
        override val isAutoGeneratedName: Boolean get() = macroNameArity.arity > 0
    }
}

/**
 * [documentation] is only called when the debug info cannot render the definition.
 */
fun clauseSource(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    debugInfo: DebugInfo?,
    documentation: () -> Documentation?
): ClauseSource? =
    debugInfoClauseSource(macroNameArity, debugInfo)
        ?: documentationClauseSource(macroNameArity, documentation())

/**
 * The head a function with default arguments is written with, when [macroNameArity] is one of the arities it answers
 * to. Elixir exports each of them, but writes the one head: `Docs` has it as the signature, else the debug info has
 * it as the default clauses that call the full-arity definition.
 */
fun definitionHead(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    debugInfo: DebugInfo?,
    documentation: () -> Documentation?
): List<String>? =
    (documentationHead(macroNameArity, documentation()) ?: debugInfoHead(macroNameArity, debugInfo))
        ?.takeIf { head -> ParameterText.arities(head).let { macroNameArity.arity in it && it.first < it.last } }

private fun debugInfoHead(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    debugInfo: DebugInfo?
): List<String>? =
    (debugInfo as? V1)?.definitions?.get(macroNameArity)?.let(DefaultArgumentClause::head)

/**
 * Every `Docs` signature of a definition's own entry, or the parameters of the first signature of the entry whose
 * defaults cover it.
 */
private sealed interface DocsEntry {
    class Own(val signatures: List<String>) : DocsEntry

    class Covering(val parameters: List<String>) : DocsEntry
}

private fun docsEntry(docs: Docs, macroNameArity: org.elixir_lang.beam.MacroNameArity): DocsEntry? =
    docs.signatures(macroNameArity)?.takeIf { it.isNotEmpty() }?.let { DocsEntry.Own(it) }
        ?: docs.covering(macroNameArity)?.signatures?.firstOrNull()
            ?.let { DocsEntry.Covering(signatureParameters(it.replace("\r", ""))) }

private fun documentationHead(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    documentation: Documentation?
): List<String>? {
    val docs = documentation?.takeIf { it.beamLanguage == "elixir" }?.docs ?: return null

    return when (val entry = docsEntry(docs, macroNameArity)) {
        is DocsEntry.Own -> signatureParameters(entry.signatures.first().replace("\r", ""))
        is DocsEntry.Covering -> entry.parameters
        null -> null
    }
}

private fun debugInfoClauseSource(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    debugInfo: DebugInfo?
): ClauseSource? =
    when (debugInfo) {
        is AbstractCodeCompileOptions ->
            when (macroNameArity.macro) {
                DEF, DEFP ->
                    debugInfo.functions.byNameArity[macroNameArity.toNameArity()]
                        ?.let { ClauseSource.ErlangAbstractCode(it) }
                else -> null
            }
        is V1 ->
            debugInfo.definitions?.get(macroNameArity)?.let { definition ->
                definition.renderedClauses()?.let { ClauseSource.ElixirDebugInfo(definition, it) }
            }
        else -> null
    }

private fun documentationClauseSource(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    documentation: Documentation?
): ClauseSource? {
    val beamLanguage = documentation?.beamLanguage ?: "elixir"
    val decompiler = decompiler(beamLanguage, macroNameArity.toNameArity()) ?: return null

    // Docs signatures read well but are not code `unquote` can use, so only the default decompiler takes them.
    val docs = if (decompiler === Default.INSTANCE) {
        documentation?.takeIf { it.beamLanguage == "elixir" }?.docs
    } else {
        null
    }

    return when (val entry = docs?.let { docsEntry(it, macroNameArity) }) {
        is DocsEntry.Own -> ClauseSource.DocsSignatures(entry.signatures)
        is DocsEntry.Covering ->
            ParameterText.covered(entry.parameters, macroNameArity.arity)
                ?.let { ClauseSource.CoveringDocsSignature(it) }
                ?: ClauseSource.Generated(decompiler, macroNameArity)
        null -> ClauseSource.Generated(decompiler, macroNameArity)
    }
}

internal val OPENERS = TokenSet.create(
    ElixirTypes.OPENING_PARENTHESIS, ElixirTypes.OPENING_BRACKET, ElixirTypes.OPENING_CURLY,
    ElixirTypes.OPENING_BIT, ElixirTypes.FN, ElixirTypes.DO
)
internal val CLOSERS = TokenSet.create(
    ElixirTypes.CLOSING_PARENTHESIS, ElixirTypes.CLOSING_BRACKET, ElixirTypes.CLOSING_CURLY,
    ElixirTypes.CLOSING_BIT, ElixirTypes.END
)

/**
 * The top-level arguments of a docs chunk signature such as `merge(map1, map2 \\ %{})`.
 */
internal fun signatureParameters(signature: String): List<String> {
    val parameters = mutableListOf<String>()
    val lexer = ElixirLexer()
    lexer.start(signature)

    var depth = 0
    var parameterStart = -1

    while (lexer.tokenType != null) {
        when (lexer.tokenType) {
            in OPENERS -> {
                depth++

                if (depth == 1 && parameterStart == -1) {
                    parameterStart = lexer.tokenEnd
                }
            }
            in CLOSERS -> {
                depth--

                if (depth == 0) {
                    signature.substring(parameterStart, lexer.tokenStart).trim().takeIf(String::isNotEmpty)?.let {
                        parameters.add(it)
                    }

                    return parameters
                }
            }
            ElixirTypes.COMMA ->
                if (depth == 1) {
                    parameters.add(signature.substring(parameterStart, lexer.tokenStart).trim())
                    parameterStart = lexer.tokenEnd
                }
        }

        lexer.advance()
    }

    return parameters
}
