# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromKind.XArityZeroUndefined do
  alias Src.EexFunctionFromKind.XArityZero
  alias Src.EexFunctionFromKind.XArityZero, as: Aliased
  import Src.EexFunctionFromKind.XArityZero

  def at_unqualified_arity_1(a, _b), do: src_eex_function_from_kind_x_arity_zero_snoc(a) # @unqualified_arity_1
end
