# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromKind.XAritySeparateUndefined do
  alias Src.EexFunctionFromKind.XAritySeparate
  alias Src.EexFunctionFromKind.XAritySeparate, as: Aliased
  import Src.EexFunctionFromKind.XAritySeparate

  def at_unqualified_arity_3(a, b), do: src_eex_function_from_kind_x_arity_separate_snoc(a, b, a) # @unqualified_arity_3
end
