# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromKind.XArityAbsent do
  alias Src.EexFunctionFromKind.XArityAbsent
  alias Src.EexFunctionFromKind.XArityAbsent, as: Aliased
  import Src.EexFunctionFromKind.XArityAbsent

  def at_qualified(a, b), do: Src.EexFunctionFromKind.XArityAbsent.src_eex_function_from_kind_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.src_eex_function_from_kind_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_eex_function_from_kind_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_eex_function_from_kind_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_eex_function_from_kind_x_arity_absent_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.EexFunctionFromKind.XArityAbsent.src_eex_function_from_kind_x_arity_absent_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.EexFunctionFromKind.XArityAbsent, :src_eex_function_from_kind_x_arity_absent_snoc, [a, b]) # @apply
end
