# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Def.XUseInjected.DefUsing do
  use ExDbgi.Def.XUseInjected.DefUsing

  def at_def_using(a, _b), do: ex_dbgi_def_x_use_injected_not_injected(a) # @def_using
end
