# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Def.XUseInjected do
  alias ExDbgi.Def.XUseInjected
  alias ExDbgi.Def.XUseInjected, as: Aliased
  import ExDbgi.Def.XUseInjected

  def at_qualified(a, b), do: ExDbgi.Def.XUseInjected.ex_dbgi_def_x_use_injected_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInjected.ex_dbgi_def_x_use_injected_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_def_x_use_injected_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_def_x_use_injected_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_def_x_use_injected_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.Def.XUseInjected.ex_dbgi_def_x_use_injected_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDbgi.Def.XUseInjected, :ex_dbgi_def_x_use_injected_snoc, [a, b]) # @apply
  def at_arity_1(a, _b), do: ExDbgi.Def.XUseInjected.ex_dbgi_def_x_use_injected_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: ExDbgi.Def.XUseInjected.Other.ex_dbgi_def_x_use_injected_snoc(a, b) # @other_qualified
end
