# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Def.XUseInjected.ImportFunctions do
  import ExDbgi.Def.XUseInjected, only: :functions

  def at_import_functions(a, b), do: ex_dbgi_def_x_use_injected_snoc(a, b) # @import_functions
end

defmodule Callers.ExDbgi.Def.XUseInjected.ImportOnly do
  import ExDbgi.Def.XUseInjected, only: [ex_dbgi_def_x_use_injected_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_dbgi_def_x_use_injected_snoc(a) # @import_only_1
end

defmodule Callers.ExDbgi.Def.XUseInjected.ImportExcept do
  import ExDbgi.Def.XUseInjected, except: [ex_dbgi_def_x_use_injected_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_dbgi_def_x_use_injected_snoc(a, b) # @import_except_2
end

defmodule Callers.ExDbgi.Def.XUseInjected.ImportFunctionsExcept do
  import ExDbgi.Def.XUseInjected, only: :functions, except: [ex_dbgi_def_x_use_injected_snoc: 1] # @import_functions_except_key

  def at_import_functions_except_2(a, b), do: ex_dbgi_def_x_use_injected_snoc(a, b) # @import_functions_except_2
end

defmodule Callers.ExDbgi.Def.XUseInjected.ImportExceptFunctions do
  import ExDbgi.Def.XUseInjected, except: [ex_dbgi_def_x_use_injected_snoc: 1], only: :functions # @import_except_functions_key

  def at_import_except_functions_2(a, b), do: ex_dbgi_def_x_use_injected_snoc(a, b) # @import_except_functions_2
end
