package org.elixir_lang.code_insight

import org.elixir_lang.PlatformTestCase
import org.elixir_lang.beam.psi.BeamFileImpl
import org.elixir_lang.beam.psi.impl.CallDefinitionImpl
import org.elixir_lang.beam.psi.impl.CallDefinitionStubImpl
import org.elixir_lang.beam.psi.stubs.ModuleStub
import org.elixir_lang.psi.ArityInterval
import java.io.File

class SignatureTest : PlatformTestCase() {
    fun testBeamDefinitionKeepsItsStoredParameters() {
        assertEquals(listOf("x", "q"), beamSignature(2, listOf("x", "q"), false).parameters)
    }

    /** A stub stores no parameters when rendering the definition failed or no decompiler accepts its name. */
    fun testBeamDefinitionWithoutStoredParametersGetsGeneratedNames() {
        assertEquals(listOf("arg1", "arg2", "arg3"), beamSignature(3, emptyList(), true).parameters)
    }

    fun testBeamZeroArityHasNoParameters() {
        assertEquals(emptyList<String>(), beamSignature(0, emptyList(), false).parameters)
    }

    /** The head covers every arity its defaults leave, so a lower arity is described by the same signature. */
    fun testBeamDefinitionWithAHeadIsDescribedByTheHeadAtEveryArityItCovers() {
        val head = listOf("a", "b \\\\ 1", "c", "d \\\\ 2")

        assertEquals(
            Signature.of(beamDefinition(4, head, false, head)),
            Signature.of(beamDefinition(2, listOf("a", "c"), false, head))
        )
        assertEquals(ArityInterval(2, 4), Signature.of(beamDefinition(3, head, false, head)).nameArityInterval.arityInterval)
    }

    fun testBeamDefinitionWithAHeadPassesTheParametersLeftAtItsArity() {
        val head = listOf("a", "b \\\\ 1", "c", "d \\\\ 2")

        assertEquals(listOf("a", "c"), Signature.parametersAt(beamDefinition(2, listOf("a", "c"), false, head)))
        assertEquals(listOf("a", "b", "c"), Signature.parametersAt(beamDefinition(3, listOf("a", "b", "c"), false, head)))
        assertEquals(listOf("a", "b", "c", "d"), Signature.parametersAt(beamDefinition(4, head, false, head)))
    }

    private fun beamSignature(arity: Int, parameters: List<String>, isAutoGeneratedName: Boolean): Signature =
        Signature.of(beamDefinition(arity, parameters, isAutoGeneratedName))

    private fun beamDefinition(
        arity: Int,
        parameters: List<String>,
        isAutoGeneratedName: Boolean,
        head: List<String> = emptyList()
    ): CallDefinitionImpl<*> {
        val bytes = File("testData/org/elixir_lang/code_insight/parameter_info/beam/ebin/queue.beam").readBytes()
        val module = BeamFileImpl.buildFileStub(bytes, "queue.beam")!!.childrenStubs.single() as ModuleStub<*>
        val stub = CallDefinitionStubImpl<CallDefinitionImpl<*>>(
            module, "def", "unrendered", arity, parameters, isAutoGeneratedName, head
        )

        return CallDefinitionImpl(stub)
    }
}
