# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromArgs.XArityZero do
  alias Src.EexFunctionFromArgs.XArityZero
  alias Src.EexFunctionFromArgs.XArityZero, as: Aliased
  import Src.EexFunctionFromArgs.XArityZero

  def at_qualified(a, b), do: Src.EexFunctionFromArgs.XArityZero.src_eex_function_from_args_x_arity_zero_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityZero.src_eex_function_from_args_x_arity_zero_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_eex_function_from_args_x_arity_zero_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_eex_function_from_args_x_arity_zero_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_eex_function_from_args_x_arity_zero_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.EexFunctionFromArgs.XArityZero.src_eex_function_from_args_x_arity_zero_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.EexFunctionFromArgs.XArityZero, :src_eex_function_from_args_x_arity_zero_snoc, [a, b]) # @apply
  def at_no_arguments(_a, _b), do: Src.EexFunctionFromArgs.XArityZero.src_eex_function_from_args_x_arity_zero_snoc # @no_arguments
end
