# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromArgs.XAritySeparateBroken do
  alias Src.EexFunctionFromArgs.XAritySeparate
  alias Src.EexFunctionFromArgs.XAritySeparate, as: Aliased
  import Src.EexFunctionFromArgs.XAritySeparate

  def at_arity_3(a, b), do: Src.EexFunctionFromArgs.XAritySeparate.src_eex_function_from_args_x_arity_separate_snoc(a, b, a) # @arity_3
end
