# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromArgs.XAritySeparate.ImportMacros do
  import Src.EexFunctionFromArgs.XAritySeparate, only: :macros

  def at_import_macros(a, b), do: src_eex_function_from_args_x_arity_separate_snoc(a, b) # @import_macros
end
