# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromArgs.XArityZeroBroken do
  alias Src.EexFunctionFromArgs.XArityZero
  alias Src.EexFunctionFromArgs.XArityZero, as: Aliased
  import Src.EexFunctionFromArgs.XArityZero

  def at_arity_1(a, _b), do: Src.EexFunctionFromArgs.XArityZero.src_eex_function_from_args_x_arity_zero_snoc(a) # @arity_1
end
