# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFromArgs.XAritySeparate.ImportFunctions do
  import Src.EexFunctionFromArgs.XAritySeparate, only: :functions

  def at_import_functions(a, b), do: src_eex_function_from_args_x_arity_separate_snoc(a, b) # @import_functions
end

defmodule Callers.Src.EexFunctionFromArgs.XAritySeparate.ImportOnly do
  import Src.EexFunctionFromArgs.XAritySeparate, only: [src_eex_function_from_args_x_arity_separate_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: src_eex_function_from_args_x_arity_separate_snoc(a) # @import_only_1
end

defmodule Callers.Src.EexFunctionFromArgs.XAritySeparate.ImportExcept do
  import Src.EexFunctionFromArgs.XAritySeparate, except: [src_eex_function_from_args_x_arity_separate_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: src_eex_function_from_args_x_arity_separate_snoc(a, b) # @import_except_2
end

defmodule Callers.Src.EexFunctionFromArgs.XAritySeparate.ImportFunctionsExcept do
  import Src.EexFunctionFromArgs.XAritySeparate, only: :functions, except: [src_eex_function_from_args_x_arity_separate_snoc: 1] # @import_functions_except_key

  def at_import_functions_except_2(a, b), do: src_eex_function_from_args_x_arity_separate_snoc(a, b) # @import_functions_except_2
end

defmodule Callers.Src.EexFunctionFromArgs.XAritySeparate.ImportExceptFunctions do
  import Src.EexFunctionFromArgs.XAritySeparate, except: [src_eex_function_from_args_x_arity_separate_snoc: 1], only: :functions # @import_except_functions_key

  def at_import_except_functions_2(a, b), do: src_eex_function_from_args_x_arity_separate_snoc(a, b) # @import_except_functions_2
end
