# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateUnresolvable.XElseKeyword do
  alias Src.DefdelegateUnresolvable.XElseKeyword
  alias Src.DefdelegateUnresolvable.XElseKeyword, as: Aliased
  import Src.DefdelegateUnresolvable.XElseKeyword

  def at_qualified(a, b), do: Src.DefdelegateUnresolvable.XElseKeyword.src_defdelegate_unresolvable_x_else_keyword_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XElseKeyword.src_defdelegate_unresolvable_x_else_keyword_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_unresolvable_x_else_keyword_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_unresolvable_x_else_keyword_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_unresolvable_x_else_keyword_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.DefdelegateUnresolvable.XElseKeyword.src_defdelegate_unresolvable_x_else_keyword_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.DefdelegateUnresolvable.XElseKeyword, :src_defdelegate_unresolvable_x_else_keyword_snoc, [a, b]) # @apply
end
