# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XAritySeparate.ImportExceptFunctions2 do
  import Src.Defmacro.XAritySeparate, except: [src_defmacro_x_arity_separate_snoc: 1], only: :functions # @import_except_functions_2_key

  def at_import_except_functions_2(a, b), do: src_defmacro_x_arity_separate_snoc(a, b) # @import_except_functions_2
end
