# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XElseList do
  alias Src.Defmacro.XElseList
  alias Src.Defmacro.XElseList, as: Aliased
  require Src.Defmacro.XElseList
  import Src.Defmacro.XElseList

  def at_qualified(a, b), do: Src.Defmacro.XElseList.src_defmacro_x_else_list_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XElseList.src_defmacro_x_else_list_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_else_list_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_else_list_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_else_list_snoc(b) # @pipe
  def at_qualified_quoted(a, b), do: Src.Defmacro.XElseList."src_defmacro_x_else_list_snoc"(a, b) # @qualified_quoted
end
