# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XElseQuoted do
  alias Src.Defmacro.XElseQuoted
  alias Src.Defmacro.XElseQuoted, as: Aliased
  require Src.Defmacro.XElseQuoted
  import Src.Defmacro.XElseQuoted

  def at_qualified(a, b), do: Src.Defmacro.XElseQuoted.src_defmacro_x_else_quoted_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XElseQuoted.src_defmacro_x_else_quoted_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_else_quoted_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_else_quoted_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_else_quoted_snoc(b) # @pipe
end
