# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XIfElse do
  alias Src.Defmacro.XIfElse
  alias Src.Defmacro.XIfElse, as: Aliased
  require Src.Defmacro.XIfElse
  import Src.Defmacro.XIfElse

  def at_qualified(a, b), do: Src.Defmacro.XIfElse.src_defmacro_x_if_else_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XIfElse.src_defmacro_x_if_else_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_if_else_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_if_else_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_if_else_snoc(b) # @pipe
  def at_arity_1(a, _b), do: Src.Defmacro.XIfElse.src_defmacro_x_if_else_snoc(a) # @arity_1
  def at_unqualified_arity_1(a, _b), do: src_defmacro_x_if_else_snoc(a) # @unqualified_arity_1
end
