# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XImportInUnless.ImportedInside do
  unless Code.ensure_loaded?(Matrix.Absent) do
    import Src.Defmacro.XImportInUnless
    def at_imported_inside(a, b), do: src_defmacro_x_import_in_unless_snoc(a, b) # @imported_inside
  end
end
