# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XImportInIf.ImportedInside do
  if Code.ensure_loaded?(Kernel) do
    import Src.Defmacro.XImportInIf
    def at_imported_inside(a, b), do: src_defmacro_x_import_in_if_snoc(a, b) # @imported_inside
  end
end
