# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XReceive do
  alias Src.Defmacro.XReceive
  alias Src.Defmacro.XReceive, as: Aliased
  require Src.Defmacro.XReceive
  import Src.Defmacro.XReceive

  def at_qualified(a, b), do: Src.Defmacro.XReceive.src_defmacro_x_receive_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XReceive.src_defmacro_x_receive_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_receive_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_receive_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_receive_snoc(b) # @pipe
end
