# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XRescue do
  alias Src.Defmacro.XRescue
  alias Src.Defmacro.XRescue, as: Aliased
  require Src.Defmacro.XRescue
  import Src.Defmacro.XRescue

  def at_qualified(a, b), do: Src.Defmacro.XRescue.src_defmacro_x_rescue_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XRescue.src_defmacro_x_rescue_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_rescue_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_rescue_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_rescue_snoc(b) # @pipe
end
