# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInQuoteTry do
  alias Src.Defmacro.XUseInQuoteTry
  alias Src.Defmacro.XUseInQuoteTry, as: Aliased
  require Src.Defmacro.XUseInQuoteTry
  require Src.Defmacro.XUseInQuoteTry.Other
  import Src.Defmacro.XUseInQuoteTry

  def at_qualified(a, b), do: Src.Defmacro.XUseInQuoteTry.src_defmacro_x_use_in_quote_try_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInQuoteTry.src_defmacro_x_use_in_quote_try_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_use_in_quote_try_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_use_in_quote_try_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_use_in_quote_try_snoc(b) # @pipe
  def at_arity_1(a, _b), do: Src.Defmacro.XUseInQuoteTry.src_defmacro_x_use_in_quote_try_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Defmacro.XUseInQuoteTry.Other.src_defmacro_x_use_in_quote_try_snoc(a, b) # @other_qualified
end
