# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjected.ImportTransitive.Middle do
  import Src.Defmacro.XUseInjected
  def middle_marker, do: :ok
end

defmodule Callers.Src.Defmacro.XUseInjected.ImportTransitive do
  import Callers.Src.Defmacro.XUseInjected.ImportTransitive.Middle

  def at_import_transitive(a, b), do: src_defmacro_x_use_injected_snoc(a, b) # @import_transitive
end

