# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjectedParens.DefUsing do
  use Src.Defmacro.XUseInjectedParens.DefUsing

  def at_def_using(a, _b), do: src_defmacro_x_use_injected_parens_not_injected(a) # @def_using
end
