# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjected.ImportFunctionsExcept2 do
  import Src.Defmacro.XUseInjected, only: :functions, except: [src_defmacro_x_use_injected_snoc: 1] # @import_functions_except_2_key

  def at_import_functions_except_2(a, b), do: src_defmacro_x_use_injected_snoc(a, b) # @import_functions_except_2
end
