# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjectedParens.Chained do
  import Src.Defmacro.XUseInjectedParens

  def at_chained(a, _b), do: src_defmacro_x_use_injected_parens_chained(a) # @chained
end

defmodule Callers.Src.Defmacro.XUseInjectedParens.ExceptChained do
  import Src.Defmacro.XUseInjectedParens, except: [src_defmacro_x_use_injected_parens_snoc: 1]

  def at_except_chained(a, _b), do: src_defmacro_x_use_injected_parens_chained(a) # @except_chained
end
