# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjectedParens.RequireOnly do
  require Src.Defmacro.XUseInjectedParens

  def at_require_only(a, b), do: src_defmacro_x_use_injected_parens_snoc(a, b) # @require_only
end
