# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjectedParens.ImportFunctions do
  import Src.Defmacro.XUseInjectedParens, only: :functions

  def at_import_functions(a, b), do: src_defmacro_x_use_injected_parens_snoc(a, b) # @import_functions
end
