# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjected.ImportMacros do
  import Src.Defmacro.XUseInjected, only: :macros

  def at_import_macros(a, b), do: src_defmacro_x_use_injected_snoc(a, b) # @import_macros
end

defmodule Callers.Src.Defmacro.XUseInjected.ImportOnly do
  import Src.Defmacro.XUseInjected, only: [src_defmacro_x_use_injected_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: src_defmacro_x_use_injected_snoc(a) # @import_only_1
end

defmodule Callers.Src.Defmacro.XUseInjected.ImportExcept do
  import Src.Defmacro.XUseInjected, except: [src_defmacro_x_use_injected_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: src_defmacro_x_use_injected_snoc(a, b) # @import_except_2
end
