# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInQuoteElseQuoted do
  alias Src.Defmacro.XUseInQuoteElseQuoted
  alias Src.Defmacro.XUseInQuoteElseQuoted, as: Aliased
  require Src.Defmacro.XUseInQuoteElseQuoted
  require Src.Defmacro.XUseInQuoteElseQuoted.Other
  import Src.Defmacro.XUseInQuoteElseQuoted

  def at_qualified(a, b), do: Src.Defmacro.XUseInQuoteElseQuoted.src_defmacro_x_use_in_quote_else_quoted_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInQuoteElseQuoted.src_defmacro_x_use_in_quote_else_quoted_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_use_in_quote_else_quoted_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_use_in_quote_else_quoted_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_use_in_quote_else_quoted_snoc(b) # @pipe
  def at_qualified_quoted(a, b), do: Src.Defmacro.XUseInQuoteElseQuoted."src_defmacro_x_use_in_quote_else_quoted_snoc"(a, b) # @qualified_quoted
  def at_arity_1(a, _b), do: Src.Defmacro.XUseInQuoteElseQuoted.src_defmacro_x_use_in_quote_else_quoted_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Defmacro.XUseInQuoteElseQuoted.Other.src_defmacro_x_use_in_quote_else_quoted_snoc(a, b) # @other_qualified
end
