# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseInjectedDefaults do
  alias Src.Defmacro.XUseInjectedDefaults
  alias Src.Defmacro.XUseInjectedDefaults, as: Aliased
  require Src.Defmacro.XUseInjectedDefaults
  import Src.Defmacro.XUseInjectedDefaults

  def at_qualified(a, b), do: Src.Defmacro.XUseInjectedDefaults.src_defmacro_x_use_injected_defaults_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInjectedDefaults.src_defmacro_x_use_injected_defaults_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_use_injected_defaults_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_use_injected_defaults_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_use_injected_defaults_snoc(b) # @pipe
  def at_arity_1(a, _b), do: Src.Defmacro.XUseInjectedDefaults.src_defmacro_x_use_injected_defaults_snoc(a) # @arity_1
  def at_unqualified_arity_1(a, _b), do: src_defmacro_x_use_injected_defaults_snoc(a) # @unqualified_arity_1
end
