# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XUseApply do
  alias Src.Defmacro.XUseApply
  alias Src.Defmacro.XUseApply, as: Aliased
  require Src.Defmacro.XUseApply
  import Src.Defmacro.XUseApply

  def at_qualified(a, b), do: Src.Defmacro.XUseApply.src_defmacro_x_use_apply_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseApply.src_defmacro_x_use_apply_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_use_apply_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_use_apply_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_use_apply_snoc(b) # @pipe
end
