# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.EexFunctionFromArgs.XArityZeroBroken do
  alias ExGen.EexFunctionFromArgs.XArityZero
  alias ExGen.EexFunctionFromArgs.XArityZero, as: Aliased
  import ExGen.EexFunctionFromArgs.XArityZero

  def at_arity_1(a, _b), do: ExGen.EexFunctionFromArgs.XArityZero.ex_gen_eex_function_from_args_x_arity_zero_snoc(a) # @arity_1
end
