# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.SrcStaleBeam do
  alias Src.Defguard.SrcStaleBeam
  alias Src.Defguard.SrcStaleBeam, as: Aliased
  require Src.Defguard.SrcStaleBeam
  import Src.Defguard.SrcStaleBeam

  def at_qualified(a, b), do: Src.Defguard.SrcStaleBeam.src_defguard_src_stale_beam_snoc(a, b) # @qualified
  def at_aliased(a, b), do: SrcStaleBeam.src_defguard_src_stale_beam_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_src_stale_beam_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_src_stale_beam_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_src_stale_beam_snoc(b) # @pipe
  def at_qualified_quoted(a, b), do: Src.Defguard.SrcStaleBeam."src_defguard_src_stale_beam_snoc"(a, b) # @qualified_quoted
end
