# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XCatch do
  alias Src.Defguard.XCatch
  alias Src.Defguard.XCatch, as: Aliased
  require Src.Defguard.XCatch
  import Src.Defguard.XCatch

  def at_qualified(a, b), do: Src.Defguard.XCatch.src_defguard_x_catch_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XCatch.src_defguard_x_catch_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_catch_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_catch_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_catch_snoc(b) # @pipe
end
