# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XElseList do
  alias Src.Defguard.XElseList
  alias Src.Defguard.XElseList, as: Aliased
  require Src.Defguard.XElseList
  import Src.Defguard.XElseList

  def at_qualified(a, b), do: Src.Defguard.XElseList.src_defguard_x_else_list_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XElseList.src_defguard_x_else_list_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_else_list_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_else_list_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_else_list_snoc(b) # @pipe
end
