# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XTryAfter do
  alias Src.Defguard.XTryAfter
  alias Src.Defguard.XTryAfter, as: Aliased
  require Src.Defguard.XTryAfter
  import Src.Defguard.XTryAfter

  def at_qualified(a, b), do: Src.Defguard.XTryAfter.src_defguard_x_try_after_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XTryAfter.src_defguard_x_try_after_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_try_after_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_try_after_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_try_after_snoc(b) # @pipe
end
