# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInjectedParens.ImportFunctionsExcept1 do
  import Src.Defguard.XUseInjectedParens, only: :functions, except: [src_defguard_x_use_injected_parens_snoc: 1] # @import_functions_except_1_key

  def at_import_functions_except_1(a, _b), do: src_defguard_x_use_injected_parens_snoc(a) # @import_functions_except_1
end
