# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseQuoteQuotedDo do
  alias Src.Defguard.XUseQuoteQuotedDo
  alias Src.Defguard.XUseQuoteQuotedDo, as: Aliased
  require Src.Defguard.XUseQuoteQuotedDo
  require Src.Defguard.XUseQuoteQuotedDo.Other
  import Src.Defguard.XUseQuoteQuotedDo

  def at_qualified(a, b), do: Src.Defguard.XUseQuoteQuotedDo.src_defguard_x_use_quote_quoted_do_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseQuoteQuotedDo.src_defguard_x_use_quote_quoted_do_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_use_quote_quoted_do_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_use_quote_quoted_do_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_use_quote_quoted_do_snoc(b) # @pipe
  def at_qualified_quoted(a, b), do: Src.Defguard.XUseQuoteQuotedDo."src_defguard_x_use_quote_quoted_do_snoc"(a, b) # @qualified_quoted
  def at_arity_1(a, _b), do: Src.Defguard.XUseQuoteQuotedDo.src_defguard_x_use_quote_quoted_do_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Defguard.XUseQuoteQuotedDo.Other.src_defguard_x_use_quote_quoted_do_snoc(a, b) # @other_qualified
end
