# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInjected.RequireOnly do
  require Src.Defguard.XUseInjected

  def at_require_only(a, b), do: src_defguard_x_use_injected_snoc(a, b) # @require_only
end
