# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInjected.ImportExceptFunctions2 do
  import Src.Defguard.XUseInjected, except: [src_defguard_x_use_injected_snoc: 1], only: :functions # @import_except_functions_2_key

  def at_import_except_functions_2(a, b), do: src_defguard_x_use_injected_snoc(a, b) # @import_except_functions_2
end
