# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInjectedParens.ImportTransitive.Middle do
  import Src.Defguard.XUseInjectedParens
  def middle_marker, do: :ok
end

defmodule Callers.Src.Defguard.XUseInjectedParens.ImportTransitive do
  import Callers.Src.Defguard.XUseInjectedParens.ImportTransitive.Middle

  def at_import_transitive(a, b), do: src_defguard_x_use_injected_parens_snoc(a, b) # @import_transitive
end

