# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInQuoteReceive do
  alias Src.Defguard.XUseInQuoteReceive
  alias Src.Defguard.XUseInQuoteReceive, as: Aliased
  require Src.Defguard.XUseInQuoteReceive
  require Src.Defguard.XUseInQuoteReceive.Other
  import Src.Defguard.XUseInQuoteReceive

  def at_qualified(a, b), do: Src.Defguard.XUseInQuoteReceive.src_defguard_x_use_in_quote_receive_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInQuoteReceive.src_defguard_x_use_in_quote_receive_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_use_in_quote_receive_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_use_in_quote_receive_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_use_in_quote_receive_snoc(b) # @pipe
  def at_arity_1(a, _b), do: Src.Defguard.XUseInQuoteReceive.src_defguard_x_use_in_quote_receive_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Defguard.XUseInQuoteReceive.Other.src_defguard_x_use_in_quote_receive_snoc(a, b) # @other_qualified
end
