# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInjectedParens.Helper do
  import Src.Defguard.XUseInjectedParens

  def at_helper(a, _b), do: src_defguard_x_use_injected_parens_helper(a) # @helper
end
