# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseInQuoteWith do
  alias Src.Defguard.XUseInQuoteWith
  alias Src.Defguard.XUseInQuoteWith, as: Aliased
  require Src.Defguard.XUseInQuoteWith
  require Src.Defguard.XUseInQuoteWith.Other
  import Src.Defguard.XUseInQuoteWith

  def at_qualified(a, b), do: Src.Defguard.XUseInQuoteWith.src_defguard_x_use_in_quote_with_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInQuoteWith.src_defguard_x_use_in_quote_with_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_use_in_quote_with_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_use_in_quote_with_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_use_in_quote_with_snoc(b) # @pipe
  def at_arity_1(a, _b), do: Src.Defguard.XUseInQuoteWith.src_defguard_x_use_in_quote_with_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Defguard.XUseInQuoteWith.Other.src_defguard_x_use_in_quote_with_snoc(a, b) # @other_qualified
end
