# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XUseQuoteLocationKeep do
  alias Src.Defguard.XUseQuoteLocationKeep
  alias Src.Defguard.XUseQuoteLocationKeep, as: Aliased
  require Src.Defguard.XUseQuoteLocationKeep
  require Src.Defguard.XUseQuoteLocationKeep.Other
  import Src.Defguard.XUseQuoteLocationKeep

  def at_qualified(a, b), do: Src.Defguard.XUseQuoteLocationKeep.src_defguard_x_use_quote_location_keep_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseQuoteLocationKeep.src_defguard_x_use_quote_location_keep_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_use_quote_location_keep_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_use_quote_location_keep_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_use_quote_location_keep_snoc(b) # @pipe
  def at_arity_1(a, _b), do: Src.Defguard.XUseQuoteLocationKeep.src_defguard_x_use_quote_location_keep_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Defguard.XUseQuoteLocationKeep.Other.src_defguard_x_use_quote_location_keep_snoc(a, b) # @other_qualified
end
