# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateUnresolvable.XDefaults.ImportFunctions do
  import ExDocs.DefdelegateUnresolvable.XDefaults, only: :functions

  def at_import_functions(a, b), do: ex_docs_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_functions
end

defmodule Callers.ExDocs.DefdelegateUnresolvable.XDefaults.ImportOnly do
  import ExDocs.DefdelegateUnresolvable.XDefaults, only: [ex_docs_defdelegate_unresolvable_x_defaults_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_docs_defdelegate_unresolvable_x_defaults_snoc(a) # @import_only_1
end

defmodule Callers.ExDocs.DefdelegateUnresolvable.XDefaults.ImportExcept do
  import ExDocs.DefdelegateUnresolvable.XDefaults, except: [ex_docs_defdelegate_unresolvable_x_defaults_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_docs_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_except_2
end

defmodule Callers.ExDocs.DefdelegateUnresolvable.XDefaults.ImportFunctionsExcept do
  import ExDocs.DefdelegateUnresolvable.XDefaults, only: :functions, except: [ex_docs_defdelegate_unresolvable_x_defaults_snoc: 1] # @import_functions_except_key

  def at_import_functions_except_2(a, b), do: ex_docs_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_functions_except_2
end

defmodule Callers.ExDocs.DefdelegateUnresolvable.XDefaults.ImportExceptFunctions do
  import ExDocs.DefdelegateUnresolvable.XDefaults, except: [ex_docs_defdelegate_unresolvable_x_defaults_snoc: 1], only: :functions # @import_except_functions_key

  def at_import_except_functions_2(a, b), do: ex_docs_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_except_functions_2
end
