# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateUnresolvable.XDefaultsHead.ImportExceptFunctions1 do
  import ExDocs.DefdelegateUnresolvable.XDefaultsHead, except: [ex_docs_defdelegate_unresolvable_x_defaults_head_snoc: 1], only: :functions # @import_except_functions_1_key

  def at_import_except_functions_1(a, _b), do: ex_docs_defdelegate_unresolvable_x_defaults_head_snoc(a) # @import_except_functions_1
end
