# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateUnresolvable.XNotACall do
  alias ExDocs.DefdelegateUnresolvable.XNotACall
  alias ExDocs.DefdelegateUnresolvable.XNotACall, as: Aliased
  import ExDocs.DefdelegateUnresolvable.XNotACall

  def at_qualified(a, b), do: ExDocs.DefdelegateUnresolvable.XNotACall.ex_docs_defdelegate_unresolvable_x_not_a_call_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XNotACall.ex_docs_defdelegate_unresolvable_x_not_a_call_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defdelegate_unresolvable_x_not_a_call_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defdelegate_unresolvable_x_not_a_call_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_defdelegate_unresolvable_x_not_a_call_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDocs.DefdelegateUnresolvable.XNotACall.ex_docs_defdelegate_unresolvable_x_not_a_call_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExDocs.DefdelegateUnresolvable.XNotACall."ex_docs_defdelegate_unresolvable_x_not_a_call_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExDocs.DefdelegateUnresolvable.XNotACall."ex_docs_defdelegate_unresolvable_x_not_a_call_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExDocs.DefdelegateUnresolvable.XNotACall, :ex_docs_defdelegate_unresolvable_x_not_a_call_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExDocs.DefdelegateUnresolvable.XNotACall, :"ex_docs_defdelegate_unresolvable_x_not_a_call_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExDocs.DefdelegateUnresolvable.XNotACall", :ex_docs_defdelegate_unresolvable_x_not_a_call_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExDocs.DefdelegateUnresolvable.XNotACall, :"#{a}ex_docs_defdelegate_unresolvable_x_not_a_call_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExDocs.DefdelegateUnresolvable.XNotACall, pick(b, :ex_docs_defdelegate_unresolvable_x_not_a_call_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExDocs.DefdelegateUnresolvable.XNotACall, pick(b, :"ex_docs_defdelegate_unresolvable_x_not_a_call_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExDocs.DefdelegateUnresolvable.XNotACall, :"ex_docs_defdelegate_unresolvable_x_not_a_call_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExDocs.DefdelegateUnresolvable.XNotACall", :ex_docs_defdelegate_unresolvable_x_not_a_call_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExDocs.DefdelegateUnresolvable.XNotACall, :"#{a}ex_docs_defdelegate_unresolvable_x_not_a_call_snoc", 2}, a, b} # @mfa_interpolated
  def at_variable(a, b), do: (fn ex_docs_defdelegate_unresolvable_x_not_a_call_snoc -> ex_docs_defdelegate_unresolvable_x_not_a_call_snoc end).({a, b}) # @variable
  def at_atom(a, b), do: {:ex_docs_defdelegate_unresolvable_x_not_a_call_snoc, a, b} # @atom
  def at_keyword(a, b), do: [ex_docs_defdelegate_unresolvable_x_not_a_call_snoc: a, b: b] # @keyword

  defp pick(opts, key), do: opts[key]
end
