# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XAritySeparate.ImportExceptFunctions1 do
  import ExDbgi.Defdelegate.XAritySeparate, except: [ex_dbgi_defdelegate_x_arity_separate_snoc: 1], only: :functions # @import_except_functions_1_key

  def at_import_except_functions_1(a, _b), do: ex_dbgi_defdelegate_x_arity_separate_snoc(a) # @import_except_functions_1
end
