# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XArityAbsent do
  alias ExDbgi.Defdelegate.XArityAbsent
  alias ExDbgi.Defdelegate.XArityAbsent, as: Aliased
  import ExDbgi.Defdelegate.XArityAbsent

  def at_qualified(a, b), do: ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defdelegate_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defdelegate_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defdelegate_x_arity_absent_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExDbgi.Defdelegate.XArityAbsent."ex_dbgi_defdelegate_x_arity_absent_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExDbgi.Defdelegate.XArityAbsent."ex_dbgi_defdelegate_x_arity_absent_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExDbgi.Defdelegate.XArityAbsent, :ex_dbgi_defdelegate_x_arity_absent_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExDbgi.Defdelegate.XArityAbsent, :"ex_dbgi_defdelegate_x_arity_absent_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExDbgi.Defdelegate.XArityAbsent", :ex_dbgi_defdelegate_x_arity_absent_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExDbgi.Defdelegate.XArityAbsent, :"#{a}ex_dbgi_defdelegate_x_arity_absent_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExDbgi.Defdelegate.XArityAbsent, pick(b, :ex_dbgi_defdelegate_x_arity_absent_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExDbgi.Defdelegate.XArityAbsent, pick(b, :"ex_dbgi_defdelegate_x_arity_absent_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExDbgi.Defdelegate.XArityAbsent, :"ex_dbgi_defdelegate_x_arity_absent_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExDbgi.Defdelegate.XArityAbsent", :ex_dbgi_defdelegate_x_arity_absent_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExDbgi.Defdelegate.XArityAbsent, :"#{a}ex_dbgi_defdelegate_x_arity_absent_snoc", 2}, a, b} # @mfa_interpolated

  defp pick(opts, key), do: opts[key]
end
