# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XAritySeparate.ImportFunctionsExcept2 do
  import ExDbgi.Defmacro.XAritySeparate, only: :functions, except: [ex_dbgi_defmacro_x_arity_separate_snoc: 1] # @import_functions_except_2_key

  def at_import_functions_except_2(a, b), do: ex_dbgi_defmacro_x_arity_separate_snoc(a, b) # @import_functions_except_2
end
