# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XDefaultsHead.ImportExceptFunctions2 do
  import ExDbgi.Defmacro.XDefaultsHead, except: [ex_dbgi_defmacro_x_defaults_head_snoc: 1], only: :functions # @import_except_functions_2_key

  def at_import_except_functions_2(a, b), do: ex_dbgi_defmacro_x_defaults_head_snoc(a, b) # @import_except_functions_2
end
