# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XUseInjected.OnlyChainedSnoc do
  import ExDbgi.Defmacro.XUseInjected, only: [ex_dbgi_defmacro_x_use_injected_chained: 1]

  def at_only_chained_snoc(a, b), do: ex_dbgi_defmacro_x_use_injected_snoc(a, b) # @only_chained_snoc
end
