# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XUseApply.UseSecret do
  use ExDbgi.Defmacro.XUseApply.Injector, :secret

  def at_use_secret(a, _b), do: ex_dbgi_defmacro_x_use_apply_secret(a) # @use_secret
end
