# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XUseInjected.Helper do
  import ExDbgi.Defmacro.XUseInjected

  def at_helper(a, _b), do: ex_dbgi_defmacro_x_use_injected_helper(a) # @helper
end
