# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XUseInjectedDefaults do
  alias ExDbgi.Defmacro.XUseInjectedDefaults
  alias ExDbgi.Defmacro.XUseInjectedDefaults, as: Aliased
  require ExDbgi.Defmacro.XUseInjectedDefaults
  import ExDbgi.Defmacro.XUseInjectedDefaults

  def at_qualified(a, b), do: ExDbgi.Defmacro.XUseInjectedDefaults.ex_dbgi_defmacro_x_use_injected_defaults_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInjectedDefaults.ex_dbgi_defmacro_x_use_injected_defaults_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defmacro_x_use_injected_defaults_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defmacro_x_use_injected_defaults_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defmacro_x_use_injected_defaults_snoc(b) # @pipe
  def at_arity_1(a, _b), do: ExDbgi.Defmacro.XUseInjectedDefaults.ex_dbgi_defmacro_x_use_injected_defaults_snoc(a) # @arity_1
  def at_unqualified_arity_1(a, _b), do: ex_dbgi_defmacro_x_use_injected_defaults_snoc(a) # @unqualified_arity_1
end
