# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XUseApply do
  alias ExDbgi.Defmacro.XUseApply
  alias ExDbgi.Defmacro.XUseApply, as: Aliased
  require ExDbgi.Defmacro.XUseApply
  import ExDbgi.Defmacro.XUseApply

  def at_qualified(a, b), do: ExDbgi.Defmacro.XUseApply.ex_dbgi_defmacro_x_use_apply_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseApply.ex_dbgi_defmacro_x_use_apply_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defmacro_x_use_apply_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defmacro_x_use_apply_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defmacro_x_use_apply_snoc(b) # @pipe
end
