# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defp.XUseInjected do
  use ExDbgi.Defp.XUseInjected.Injector

  def local_site(a, b), do: ex_dbgi_defp_x_use_injected_snoc(a, b) # @local

  def uses(a, b) do
    {
      ex_dbgi_defp_x_use_injected_snoc(a), # @uses_0
      a,
      b
    }
  end
end
