# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defmacro.XUseApply do
  use ExDbgi.Defmacro.XUseApply.Injector, :view

  def local_site(a, b), do: ex_dbgi_defmacro_x_use_apply_snoc(a, b) # @local
end
