# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defp.XUseInjected.PrivateUsing do
  defmacrop __using__(_) do
    quote do
      def ex_dbgi_defp_x_use_injected_privately_injected(x), do: x
    end
  end

  def target_marker, do: :ok
end
