# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defmacro.XUseInjectedDefaults.DefUsing do
  def __using__(_) do
    quote do
      def ex_dbgi_defmacro_x_use_injected_defaults_not_injected(x), do: x
    end
  end

  def target_marker, do: :ok
end
