# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defp.XUseInjected.Injector do
  defmacro __using__(_) do
    quote do
      use ExDbgi.Defp.XUseInjected.Inner
      import ExDbgi.Defp.XUseInjected.Helpers, warn: false
      defp ex_dbgi_defp_x_use_injected_hidden(x), do: x
      defp ex_dbgi_defp_x_use_injected_snoc(q), do: {q}
      defp ex_dbgi_defp_x_use_injected_snoc(q, x), do: {q, x}
    end
  end

  def target_marker, do: :ok
end
