# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.EexFunctionFromKind.XNotACall do
  require EEx

  @kind :def
  EEx.function_from_string(@kind, :ex_dbgi_eex_function_from_kind_x_not_a_call_snoc, "<%= inspect({q, x}) %>", [:q, :x])

  def local_site(a, b), do: ex_dbgi_eex_function_from_kind_x_not_a_call_snoc(a, b) # @local
end
