# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Def.XUseInjectedDefaults.Injector do
  defmacro __using__(_) do
    quote do
      use ExDbgi.Def.XUseInjectedDefaults.Inner
      import ExDbgi.Def.XUseInjectedDefaults.Helpers, warn: false
      defp ex_dbgi_def_x_use_injected_defaults_hidden(x), do: x
      def ex_dbgi_def_x_use_injected_defaults_snoc(a \\ nil, b \\ nil)
      def ex_dbgi_def_x_use_injected_defaults_snoc(a, b) when is_nil(a), do: {a, b}
      def ex_dbgi_def_x_use_injected_defaults_snoc(a, b), do: {a, b}
    end
  end

  def target_marker, do: :ok
end
