# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.EexFunctionFromArgs.XArity do
  require EEx

  @args [:q, :x]
  EEx.function_from_string(:def, :ex_dbgi_eex_function_from_args_x_arity_snoc, "<%= inspect({q, x}) %>", @args)
  @args [:q, :x, :y]
  EEx.function_from_string(:def, :ex_dbgi_eex_function_from_args_x_arity_snoc, "<%= inspect({q, x, y}) %>", @args)

  def local_site(a, b), do: ex_dbgi_eex_function_from_args_x_arity_snoc(a, b) # @local
end
