# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defp.XUseApply do
  use ExDbgi.Defp.XUseApply.Injector, :view

  def local_site(a, b), do: ex_dbgi_defp_x_use_apply_snoc(a, b) # @local

  def uses(a, b) do
    {
      a,
      b
    }
  end
end
