# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.EexFunctionFromArgs.XAritySeparate do
  require EEx

  @args []
  EEx.function_from_string(:def, :ex_docs_eex_function_from_args_x_arity_separate_snoc, "<%= inspect({}) %>", @args)
  @args [:a]
  EEx.function_from_string(:def, :ex_docs_eex_function_from_args_x_arity_separate_snoc, "<%= inspect({a}) %>", @args)
  @args [:a, :b]
  EEx.function_from_string(:def, :ex_docs_eex_function_from_args_x_arity_separate_snoc, "<%= inspect({a, b}) %>", @args)

  def local_site(a, b), do: ex_docs_eex_function_from_args_x_arity_separate_snoc(a, b) # @local
end
