# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.EexFunctionFromKind.XArityAbsent do
  require EEx

  @kind :def
  EEx.function_from_string(@kind, :ex_docs_eex_function_from_kind_x_arity_absent_snoc, "<%= inspect({q, x}) %>", [:q, :x])

  def local_site(a, b), do: ex_docs_eex_function_from_kind_x_arity_absent_snoc(a, b) # @local
end
