# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XCompileTimeCall.CalledInDoTuple do
  if Code.ensure_loaded?(Kernel), do: {:k, src_def_x_compile_time_call_snoc(1, 2)} # @called_in_do_tuple

  def src_def_x_compile_time_call_snoc(q, x), do: {q, x}
end
