# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XImportInBodyIf.ImportedAfter do
  def at_imported_after(a, b) do
    if Code.ensure_loaded?(Kernel) do
      import Src.Def.XImportInBodyIf
    end

    src_def_x_import_in_body_if_snoc(a, b) # @imported_after
  end
end
