# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XInterpolatedAtom do

  def at_nested(a, b), do: {:"src_def_x_interpolated_atom_nes#{"t"}ed", a, b} # @nested
  def at_unescaped(a, b), do: {:"src_def_x_interpolated_atom_a(#{"b"}", a, b} # @unescaped
  def at_unanchored(a, b), do: {:"src_def_x_interpolated_atom_ba#{"r"}e", a, b} # @unanchored
end

defmodule :src_def_x_interpolated_atom_nested do end

defmodule :src_def_x_interpolated_atom_bare do end

defmodule :src_def_x_interpolated_atom_bare_extra do end
