# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XModuledocSince do
  alias Src.Def.XModuledocSince

  def at_module_qualified(_a, _b), do: Src.Def.XModuledocSince # @module_qualified
  def at_module_aliased(_a, _b), do: XModuledocSince # @module_aliased
end
