# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XModuledocFile do
  alias Src.Def.XModuledocFile

  def at_module_qualified(_a, _b), do: Src.Def.XModuledocFile # @module_qualified
  def at_module_aliased(_a, _b), do: XModuledocFile # @module_aliased
end
