# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseInQuoteCond do
  alias Src.Def.XUseInQuoteCond
  alias Src.Def.XUseInQuoteCond, as: Aliased
  import Src.Def.XUseInQuoteCond

  def at_qualified(a, b), do: Src.Def.XUseInQuoteCond.src_def_x_use_in_quote_cond_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInQuoteCond.src_def_x_use_in_quote_cond_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_def_x_use_in_quote_cond_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_def_x_use_in_quote_cond_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_def_x_use_in_quote_cond_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.Def.XUseInQuoteCond.src_def_x_use_in_quote_cond_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: Src.Def.XUseInQuoteCond."src_def_x_use_in_quote_cond_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&Src.Def.XUseInQuoteCond."src_def_x_use_in_quote_cond_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(Src.Def.XUseInQuoteCond, :src_def_x_use_in_quote_cond_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(Src.Def.XUseInQuoteCond, :"src_def_x_use_in_quote_cond_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.Src.Def.XUseInQuoteCond", :src_def_x_use_in_quote_cond_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(Src.Def.XUseInQuoteCond, :"#{a}src_def_x_use_in_quote_cond_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(Src.Def.XUseInQuoteCond, pick(b, :src_def_x_use_in_quote_cond_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(Src.Def.XUseInQuoteCond, pick(b, :"src_def_x_use_in_quote_cond_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{Src.Def.XUseInQuoteCond, :"src_def_x_use_in_quote_cond_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.Src.Def.XUseInQuoteCond", :src_def_x_use_in_quote_cond_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{Src.Def.XUseInQuoteCond, :"#{a}src_def_x_use_in_quote_cond_snoc", 2}, a, b} # @mfa_interpolated
  def at_arity_1(a, _b), do: Src.Def.XUseInQuoteCond.src_def_x_use_in_quote_cond_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Def.XUseInQuoteCond.Other.src_def_x_use_in_quote_cond_snoc(a, b) # @other_qualified

  defp pick(opts, key), do: opts[key]
end
