# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseInjectedParens.ImportMacros do
  import Src.Def.XUseInjectedParens, only: :macros

  def at_import_macros(a, b), do: src_def_x_use_injected_parens_snoc(a, b) # @import_macros
end
