# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseInjectedParens.Hidden do
  import Src.Def.XUseInjectedParens

  def at_hidden(a, _b), do: src_def_x_use_injected_parens_hidden(a) # @hidden
end
