# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseApply.UseSecret do
  use Src.Def.XUseApply.Injector, :secret

  def at_use_secret(a, _b), do: src_def_x_use_apply_secret(a) # @use_secret
end
