# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseInjected.ImportExcept1 do
  import Src.Def.XUseInjected, except: [src_def_x_use_injected_snoc: 1] # @import_except_1_key

  def at_import_except_1(a, _b), do: src_def_x_use_injected_snoc(a) # @import_except_1
end
