# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseInjected.PrivateUsing do
  use Src.Def.XUseInjected.PrivateUsing

  def at_private_using(a, _b), do: src_def_x_use_injected_privately_injected(a) # @private_using
end
