# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XUseInQuoteUnless do
  alias Src.Def.XUseInQuoteUnless
  alias Src.Def.XUseInQuoteUnless, as: Aliased
  import Src.Def.XUseInQuoteUnless

  def at_qualified(a, b), do: Src.Def.XUseInQuoteUnless.src_def_x_use_in_quote_unless_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInQuoteUnless.src_def_x_use_in_quote_unless_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_def_x_use_in_quote_unless_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_def_x_use_in_quote_unless_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_def_x_use_in_quote_unless_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.Def.XUseInQuoteUnless.src_def_x_use_in_quote_unless_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.Def.XUseInQuoteUnless, :src_def_x_use_in_quote_unless_snoc, [a, b]) # @apply
  def at_arity_1(a, _b), do: Src.Def.XUseInQuoteUnless.src_def_x_use_in_quote_unless_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: Src.Def.XUseInQuoteUnless.Other.src_def_x_use_in_quote_unless_snoc(a, b) # @other_qualified
end
