# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XAritySeparate.ImportFunctionsExcept1 do
  import Src.DefdelegateCompiled.XAritySeparate, only: :functions, except: [src_defdelegate_compiled_x_arity_separate_snoc: 1] # @import_functions_except_1_key

  def at_import_functions_except_1(a, _b), do: src_defdelegate_compiled_x_arity_separate_snoc(a) # @import_functions_except_1
end
