# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportFunctions do
  import Src.DefdelegateCompiled.XDefaultsHead, only: :functions

  def at_import_functions(a, b), do: src_defdelegate_compiled_x_defaults_head_snoc(a, b) # @import_functions
end

defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportOnly do
  import Src.DefdelegateCompiled.XDefaultsHead, only: [src_defdelegate_compiled_x_defaults_head_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: src_defdelegate_compiled_x_defaults_head_snoc(a) # @import_only_1
end

defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportExcept do
  import Src.DefdelegateCompiled.XDefaultsHead, except: [src_defdelegate_compiled_x_defaults_head_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: src_defdelegate_compiled_x_defaults_head_snoc(a, b) # @import_except_2
end

defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportFunctionsExcept do
  import Src.DefdelegateCompiled.XDefaultsHead, only: :functions, except: [src_defdelegate_compiled_x_defaults_head_snoc: 1] # @import_functions_except_key

  def at_import_functions_except_2(a, b), do: src_defdelegate_compiled_x_defaults_head_snoc(a, b) # @import_functions_except_2
end

defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportExceptFunctions do
  import Src.DefdelegateCompiled.XDefaultsHead, except: [src_defdelegate_compiled_x_defaults_head_snoc: 1], only: :functions # @import_except_functions_key

  def at_import_except_functions_2(a, b), do: src_defdelegate_compiled_x_defaults_head_snoc(a, b) # @import_except_functions_2
end
