# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XReceive do
  alias Src.DefdelegateCompiled.XReceive
  alias Src.DefdelegateCompiled.XReceive, as: Aliased
  import Src.DefdelegateCompiled.XReceive

  def at_qualified(a, b), do: Src.DefdelegateCompiled.XReceive.src_defdelegate_compiled_x_receive_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XReceive.src_defdelegate_compiled_x_receive_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_compiled_x_receive_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_compiled_x_receive_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_compiled_x_receive_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.DefdelegateCompiled.XReceive.src_defdelegate_compiled_x_receive_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.DefdelegateCompiled.XReceive, :src_defdelegate_compiled_x_receive_snoc, [a, b]) # @apply
end
