# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defp.W2.ImportOnlyPrivate do
  import ExDbgi.Defp.W2, only: [ex_dbgi_defp_w2_snoc: 1] # @import_only_private_key


end
