# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defp.XAritySeparate.ImportOnlyPrivate do
  import ExDbgi.Defp.XAritySeparate, only: [ex_dbgi_defp_x_arity_separate_snoc: 1] # @import_only_private_key


end
