# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defp.XDefaults.ImportOnlyPrivate do
  import ExDbgi.Defp.XDefaults, only: [ex_dbgi_defp_x_defaults_snoc: 1] # @import_only_private_key


end
