# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateAs.W2 do
  alias ExDbgi.DefdelegateAs.W2
  alias ExDbgi.DefdelegateAs.W2, as: Aliased
  import ExDbgi.DefdelegateAs.W2

  def at_qualified(a, b), do: ExDbgi.DefdelegateAs.W2.ex_dbgi_defdelegate_as_w2_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W2.ex_dbgi_defdelegate_as_w2_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defdelegate_as_w2_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defdelegate_as_w2_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defdelegate_as_w2_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.DefdelegateAs.W2.ex_dbgi_defdelegate_as_w2_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExDbgi.DefdelegateAs.W2."ex_dbgi_defdelegate_as_w2_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExDbgi.DefdelegateAs.W2."ex_dbgi_defdelegate_as_w2_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExDbgi.DefdelegateAs.W2, :ex_dbgi_defdelegate_as_w2_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExDbgi.DefdelegateAs.W2, :"ex_dbgi_defdelegate_as_w2_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExDbgi.DefdelegateAs.W2", :ex_dbgi_defdelegate_as_w2_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExDbgi.DefdelegateAs.W2, :"#{a}ex_dbgi_defdelegate_as_w2_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExDbgi.DefdelegateAs.W2, pick(b, :ex_dbgi_defdelegate_as_w2_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExDbgi.DefdelegateAs.W2, pick(b, :"ex_dbgi_defdelegate_as_w2_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExDbgi.DefdelegateAs.W2, :"ex_dbgi_defdelegate_as_w2_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExDbgi.DefdelegateAs.W2", :ex_dbgi_defdelegate_as_w2_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExDbgi.DefdelegateAs.W2, :"#{a}ex_dbgi_defdelegate_as_w2_snoc", 2}, a, b} # @mfa_interpolated
  def at_second_qualified(a, b), do: ExDbgi.DefdelegateAs.W2.ex_dbgi_defdelegate_as_w2_snoc(a, b) # @second_qualified
  def at_arity_1(a, _b), do: ExDbgi.DefdelegateAs.W2.ex_dbgi_defdelegate_as_w2_snoc(a) # @arity_1
  def at_arity_3(a, b), do: ExDbgi.DefdelegateAs.W2.ex_dbgi_defdelegate_as_w2_snoc(a, b, a) # @arity_3

  defp pick(opts, key), do: opts[key]
end
