# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defp.XUseInjectedParens.ImportOnlyPrivate do
  import Src.Defp.XUseInjectedParens, only: [src_defp_x_use_injected_parens_snoc: 1] # @import_only_private_key


end
