# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defp.XUseInjectedParens.ImportWhole do
  import Src.Defp.XUseInjectedParens

  def at_import_whole(a, b), do: src_defp_x_use_injected_parens_snoc(a, b) # @import_whole
end
