# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.EexFunctionFromKind.XArity do
  require EEx

  @kind :def
  EEx.function_from_string(@kind, :ex_gen_eex_function_from_kind_x_arity_snoc, "<%= inspect({q, x}) %>", [:q, :x])
  @kind :def
  EEx.function_from_string(@kind, :ex_gen_eex_function_from_kind_x_arity_snoc, "<%= inspect({q, x, y}) %>", [:q, :x, :y])

  def local_site(a, b), do: ex_gen_eex_function_from_kind_x_arity_snoc(a, b) # @local
end
