# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.EexFunctionFromArgs.XOtherModule.Other do
  require EEx

  @args [:q, :x]
  EEx.function_from_string(:def, :ex_gen_eex_function_from_args_x_other_module_snoc, "<%= inspect({q, x}) %>", @args)
end
