# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.EexFunctionFromArgs.W1 do
  require EEx

  @args [:q, :x]
  EEx.function_from_string(:def, :ex_gen_eex_function_from_args_w1_snoc, "<%= inspect({q, x}) %>", @args)

  def local_site(a, b), do: ex_gen_eex_function_from_args_w1_snoc(a, b) # @local
end
