# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XDefaults.ImportFunctionsExcept1 do
  import ExDocs.Def.XDefaults, only: :functions, except: [ex_docs_def_x_defaults_snoc: 1] # @import_functions_except_1_key

  def at_import_functions_except_1(a, _b), do: ex_docs_def_x_defaults_snoc(a) # @import_functions_except_1
end
