# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.W2.ImportFunctionsExcept1 do
  import :erl_abst_def_w2, only: :functions, except: [erl_abst_def_w2_snoc: 1] # @import_functions_except_1_key

  def at_import_functions_except_1(a, _b), do: erl_abst_def_w2_snoc(a) # @import_functions_except_1
end
