# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XOtherModule do
  import :erl_abst_def_x_other_module

  def at_qualified(a, b), do: :erl_abst_def_x_other_module.erl_abst_def_x_other_module_snoc(a, b) # @qualified
  def at_unqualified(a, b), do: erl_abst_def_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> erl_abst_def_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&:erl_abst_def_x_other_module.erl_abst_def_x_other_module_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: :erl_abst_def_x_other_module."erl_abst_def_x_other_module_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&:erl_abst_def_x_other_module."erl_abst_def_x_other_module_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(:erl_abst_def_x_other_module, :erl_abst_def_x_other_module_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(:erl_abst_def_x_other_module, :"erl_abst_def_x_other_module_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"erl_abst_def_x_other_module", :erl_abst_def_x_other_module_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(:erl_abst_def_x_other_module, :"#{a}erl_abst_def_x_other_module_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(:erl_abst_def_x_other_module, pick(b, :erl_abst_def_x_other_module_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(:erl_abst_def_x_other_module, pick(b, :"erl_abst_def_x_other_module_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{:erl_abst_def_x_other_module, :"erl_abst_def_x_other_module_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"erl_abst_def_x_other_module", :erl_abst_def_x_other_module_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{:erl_abst_def_x_other_module, :"#{a}erl_abst_def_x_other_module_snoc", 2}, a, b} # @mfa_interpolated
  def at_other_qualified(a, b), do: :erl_abst_def_x_other_module_other.erl_abst_def_x_other_module_snoc(a, b) # @other_qualified

  defp pick(opts, key), do: opts[key]
end
