# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.EexFunctionFromArgs.XArityZeroBroken do
  alias ExDocs.EexFunctionFromArgs.XArityZero
  alias ExDocs.EexFunctionFromArgs.XArityZero, as: Aliased
  import ExDocs.EexFunctionFromArgs.XArityZero

  def at_arity_1(a, _b), do: ExDocs.EexFunctionFromArgs.XArityZero.ex_docs_eex_function_from_args_x_arity_zero_snoc(a) # @arity_1
end
