# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defdelegate.W1 do
  alias ExGen.Defdelegate.W1
  alias ExGen.Defdelegate.W1, as: Aliased
  import ExGen.Defdelegate.W1

  def at_qualified(a, b), do: ExGen.Defdelegate.W1.ex_gen_defdelegate_w1_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W1.ex_gen_defdelegate_w1_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_defdelegate_w1_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_defdelegate_w1_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_defdelegate_w1_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExGen.Defdelegate.W1.ex_gen_defdelegate_w1_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExGen.Defdelegate.W1."ex_gen_defdelegate_w1_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExGen.Defdelegate.W1."ex_gen_defdelegate_w1_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExGen.Defdelegate.W1, :ex_gen_defdelegate_w1_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExGen.Defdelegate.W1, :"ex_gen_defdelegate_w1_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExGen.Defdelegate.W1", :ex_gen_defdelegate_w1_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExGen.Defdelegate.W1, :"#{a}ex_gen_defdelegate_w1_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExGen.Defdelegate.W1, pick(b, :ex_gen_defdelegate_w1_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExGen.Defdelegate.W1, pick(b, :"ex_gen_defdelegate_w1_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExGen.Defdelegate.W1, :"ex_gen_defdelegate_w1_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExGen.Defdelegate.W1", :ex_gen_defdelegate_w1_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExGen.Defdelegate.W1, :"#{a}ex_gen_defdelegate_w1_snoc", 2}, a, b} # @mfa_interpolated

  defp pick(opts, key), do: opts[key]
end
