# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Defp.XAritySeparate.ImportOnlyPrivate do
  import :erl_abst_defp_x_arity_separate, only: [erl_abst_defp_x_arity_separate_snoc: 1] # @import_only_private_key


end
