# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFromKind.XArityAbsentUndefined do
  alias ExDbgi.EexFunctionFromKind.XArityAbsent
  alias ExDbgi.EexFunctionFromKind.XArityAbsent, as: Aliased
  import ExDbgi.EexFunctionFromKind.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_dbgi_eex_function_from_kind_x_arity_absent_snoc(a) # @unqualified_arity_1
end
