# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFromKind.XArityZeroBroken do
  alias ExDbgi.EexFunctionFromKind.XArityZero
  alias ExDbgi.EexFunctionFromKind.XArityZero, as: Aliased
  import ExDbgi.EexFunctionFromKind.XArityZero

  def at_arity_1(a, _b), do: ExDbgi.EexFunctionFromKind.XArityZero.ex_dbgi_eex_function_from_kind_x_arity_zero_snoc(a) # @arity_1
end
