# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFromKind.XAritySeparateBroken do
  alias ExDbgi.EexFunctionFromKind.XAritySeparate
  alias ExDbgi.EexFunctionFromKind.XAritySeparate, as: Aliased
  import ExDbgi.EexFunctionFromKind.XAritySeparate

  def at_arity_3(a, b), do: ExDbgi.EexFunctionFromKind.XAritySeparate.ex_dbgi_eex_function_from_kind_x_arity_separate_snoc(a, b, a) # @arity_3
end
