# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFromKind.XOtherModule do
  alias ExDbgi.EexFunctionFromKind.XOtherModule
  alias ExDbgi.EexFunctionFromKind.XOtherModule, as: Aliased
  import ExDbgi.EexFunctionFromKind.XOtherModule

  def at_qualified(a, b), do: ExDbgi.EexFunctionFromKind.XOtherModule.ex_dbgi_eex_function_from_kind_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.ex_dbgi_eex_function_from_kind_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_eex_function_from_kind_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_eex_function_from_kind_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_eex_function_from_kind_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.EexFunctionFromKind.XOtherModule.ex_dbgi_eex_function_from_kind_x_other_module_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExDbgi.EexFunctionFromKind.XOtherModule."ex_dbgi_eex_function_from_kind_x_other_module_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExDbgi.EexFunctionFromKind.XOtherModule."ex_dbgi_eex_function_from_kind_x_other_module_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExDbgi.EexFunctionFromKind.XOtherModule, :ex_dbgi_eex_function_from_kind_x_other_module_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExDbgi.EexFunctionFromKind.XOtherModule, :"ex_dbgi_eex_function_from_kind_x_other_module_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExDbgi.EexFunctionFromKind.XOtherModule", :ex_dbgi_eex_function_from_kind_x_other_module_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExDbgi.EexFunctionFromKind.XOtherModule, :"#{a}ex_dbgi_eex_function_from_kind_x_other_module_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExDbgi.EexFunctionFromKind.XOtherModule, pick(b, :ex_dbgi_eex_function_from_kind_x_other_module_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExDbgi.EexFunctionFromKind.XOtherModule, pick(b, :"ex_dbgi_eex_function_from_kind_x_other_module_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExDbgi.EexFunctionFromKind.XOtherModule, :"ex_dbgi_eex_function_from_kind_x_other_module_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExDbgi.EexFunctionFromKind.XOtherModule", :ex_dbgi_eex_function_from_kind_x_other_module_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExDbgi.EexFunctionFromKind.XOtherModule, :"#{a}ex_dbgi_eex_function_from_kind_x_other_module_snoc", 2}, a, b} # @mfa_interpolated
  def at_other_qualified(a, b), do: ExDbgi.EexFunctionFromKind.XOtherModule.Other.ex_dbgi_eex_function_from_kind_x_other_module_snoc(a, b) # @other_qualified

  defp pick(opts, key), do: opts[key]
end
