# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFromArgs.XAritySeparateUndefined do
  alias ExDbgi.EexFunctionFromArgs.XAritySeparate
  alias ExDbgi.EexFunctionFromArgs.XAritySeparate, as: Aliased
  import ExDbgi.EexFunctionFromArgs.XAritySeparate

  def at_unqualified_arity_3(a, b), do: ex_dbgi_eex_function_from_args_x_arity_separate_snoc(a, b, a) # @unqualified_arity_3
end
