# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFromArgs.XAritySeparate.RequireOnly do
  require ExDbgi.EexFunctionFromArgs.XAritySeparate

  def at_require_only(a, b), do: ex_dbgi_eex_function_from_args_x_arity_separate_snoc(a, b) # @require_only
end
