# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defdelegate.XNfc do
  alias Src.Defdelegate.XNfc
  alias Src.Defdelegate.XNfc, as: Aliased
  import Src.Defdelegate.XNfc

  def at_qualified(a, b), do: Src.Defdelegate.XNfc.src_defdelegate_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.src_defdelegate_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_x_nfc_snoć(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_x_nfc_snoć(b) # @pipe
  def at_capture(a, b), do: {&Src.Defdelegate.XNfc.src_defdelegate_x_nfc_snoć/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: Src.Defdelegate.XNfc."src_defdelegate_x_nfc_snoć"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&Src.Defdelegate.XNfc."src_defdelegate_x_nfc_snoć"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(Src.Defdelegate.XNfc, :src_defdelegate_x_nfc_snoć, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(Src.Defdelegate.XNfc, :"src_defdelegate_x_nfc_snoć", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.Src.Defdelegate.XNfc", :src_defdelegate_x_nfc_snoć, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(Src.Defdelegate.XNfc, :"#{a}src_defdelegate_x_nfc_snoć", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(Src.Defdelegate.XNfc, pick(b, :src_defdelegate_x_nfc_snoć), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(Src.Defdelegate.XNfc, pick(b, :"src_defdelegate_x_nfc_snoć"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{Src.Defdelegate.XNfc, :"src_defdelegate_x_nfc_snoć", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.Src.Defdelegate.XNfc", :src_defdelegate_x_nfc_snoć, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{Src.Defdelegate.XNfc, :"#{a}src_defdelegate_x_nfc_snoć", 2}, a, b} # @mfa_interpolated
  def at_atom(a, b), do: {:src_defdelegate_x_nfc_snoć, a, b} # @atom

  defp pick(opts, key), do: opts[key]
end
