# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defdelegate.XNotACall do
  alias Src.Defdelegate.XNotACall
  alias Src.Defdelegate.XNotACall, as: Aliased
  import Src.Defdelegate.XNotACall

  def at_qualified(a, b), do: Src.Defdelegate.XNotACall.src_defdelegate_x_not_a_call_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XNotACall.src_defdelegate_x_not_a_call_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_x_not_a_call_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_x_not_a_call_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_x_not_a_call_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.Defdelegate.XNotACall.src_defdelegate_x_not_a_call_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: Src.Defdelegate.XNotACall."src_defdelegate_x_not_a_call_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&Src.Defdelegate.XNotACall."src_defdelegate_x_not_a_call_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(Src.Defdelegate.XNotACall, :src_defdelegate_x_not_a_call_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(Src.Defdelegate.XNotACall, :"src_defdelegate_x_not_a_call_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.Src.Defdelegate.XNotACall", :src_defdelegate_x_not_a_call_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(Src.Defdelegate.XNotACall, :"#{a}src_defdelegate_x_not_a_call_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(Src.Defdelegate.XNotACall, pick(b, :src_defdelegate_x_not_a_call_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(Src.Defdelegate.XNotACall, pick(b, :"src_defdelegate_x_not_a_call_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{Src.Defdelegate.XNotACall, :"src_defdelegate_x_not_a_call_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.Src.Defdelegate.XNotACall", :src_defdelegate_x_not_a_call_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{Src.Defdelegate.XNotACall, :"#{a}src_defdelegate_x_not_a_call_snoc", 2}, a, b} # @mfa_interpolated
  def at_variable(a, b), do: (fn src_defdelegate_x_not_a_call_snoc -> src_defdelegate_x_not_a_call_snoc end).({a, b}) # @variable
  def at_atom(a, b), do: {:src_defdelegate_x_not_a_call_snoc, a, b} # @atom
  def at_keyword(a, b), do: [src_defdelegate_x_not_a_call_snoc: a, b: b] # @keyword

  defp pick(opts, key), do: opts[key]
end
