# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.EexFunctionFromKind.XAritySeparate do
  alias ExDocs.EexFunctionFromKind.XAritySeparate
  alias ExDocs.EexFunctionFromKind.XAritySeparate, as: Aliased
  import ExDocs.EexFunctionFromKind.XAritySeparate

  def at_qualified(a, b), do: ExDocs.EexFunctionFromKind.XAritySeparate.ex_docs_eex_function_from_kind_x_arity_separate_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XAritySeparate.ex_docs_eex_function_from_kind_x_arity_separate_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_eex_function_from_kind_x_arity_separate_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_eex_function_from_kind_x_arity_separate_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_eex_function_from_kind_x_arity_separate_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDocs.EexFunctionFromKind.XAritySeparate.ex_docs_eex_function_from_kind_x_arity_separate_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExDocs.EexFunctionFromKind.XAritySeparate."ex_docs_eex_function_from_kind_x_arity_separate_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExDocs.EexFunctionFromKind.XAritySeparate."ex_docs_eex_function_from_kind_x_arity_separate_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExDocs.EexFunctionFromKind.XAritySeparate, :ex_docs_eex_function_from_kind_x_arity_separate_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExDocs.EexFunctionFromKind.XAritySeparate, :"ex_docs_eex_function_from_kind_x_arity_separate_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExDocs.EexFunctionFromKind.XAritySeparate", :ex_docs_eex_function_from_kind_x_arity_separate_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExDocs.EexFunctionFromKind.XAritySeparate, :"#{a}ex_docs_eex_function_from_kind_x_arity_separate_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExDocs.EexFunctionFromKind.XAritySeparate, pick(b, :ex_docs_eex_function_from_kind_x_arity_separate_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExDocs.EexFunctionFromKind.XAritySeparate, pick(b, :"ex_docs_eex_function_from_kind_x_arity_separate_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExDocs.EexFunctionFromKind.XAritySeparate, :"ex_docs_eex_function_from_kind_x_arity_separate_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExDocs.EexFunctionFromKind.XAritySeparate", :ex_docs_eex_function_from_kind_x_arity_separate_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExDocs.EexFunctionFromKind.XAritySeparate, :"#{a}ex_docs_eex_function_from_kind_x_arity_separate_snoc", 2}, a, b} # @mfa_interpolated
  def at_no_arguments(_a, _b), do: ExDocs.EexFunctionFromKind.XAritySeparate.ex_docs_eex_function_from_kind_x_arity_separate_snoc # @no_arguments
  def at_arity_1(a, _b), do: ExDocs.EexFunctionFromKind.XAritySeparate.ex_docs_eex_function_from_kind_x_arity_separate_snoc(a) # @arity_1

  defp pick(opts, key), do: opts[key]
end
