# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.EexFunctionFromKind.XAritySeparateBroken do
  alias ExDocs.EexFunctionFromKind.XAritySeparate
  alias ExDocs.EexFunctionFromKind.XAritySeparate, as: Aliased
  import ExDocs.EexFunctionFromKind.XAritySeparate

  def at_arity_3(a, b), do: ExDocs.EexFunctionFromKind.XAritySeparate.ex_docs_eex_function_from_kind_x_arity_separate_snoc(a, b, a) # @arity_3
end
