# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XUseInjected.Chained do
  import ExDbgi.Defguard.XUseInjected

  def at_chained(a, _b), do: ex_dbgi_defguard_x_use_injected_chained(a) # @chained
end

defmodule Callers.ExDbgi.Defguard.XUseInjected.ExceptChained do
  import ExDbgi.Defguard.XUseInjected, except: [ex_dbgi_defguard_x_use_injected_snoc: 1]

  def at_except_chained(a, _b), do: ex_dbgi_defguard_x_use_injected_chained(a) # @except_chained
end
