# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XUseInjected do
  alias ExDbgi.Defguard.XUseInjected
  alias ExDbgi.Defguard.XUseInjected, as: Aliased
  require ExDbgi.Defguard.XUseInjected
  require ExDbgi.Defguard.XUseInjected.Other
  import ExDbgi.Defguard.XUseInjected

  def at_qualified(a, b), do: ExDbgi.Defguard.XUseInjected.ex_dbgi_defguard_x_use_injected_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XUseInjected.ex_dbgi_defguard_x_use_injected_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defguard_x_use_injected_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defguard_x_use_injected_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defguard_x_use_injected_snoc(b) # @pipe
  def at_arity_1(a, _b), do: ExDbgi.Defguard.XUseInjected.ex_dbgi_defguard_x_use_injected_snoc(a) # @arity_1
  def at_other_qualified(a, b), do: ExDbgi.Defguard.XUseInjected.Other.ex_dbgi_defguard_x_use_injected_snoc(a, b) # @other_qualified
end
