# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XUseInjected.ImportTransitive.Middle do
  import ExDbgi.Defguard.XUseInjected
  def middle_marker, do: :ok
end

defmodule Callers.ExDbgi.Defguard.XUseInjected.ImportTransitive do
  import Callers.ExDbgi.Defguard.XUseInjected.ImportTransitive.Middle

  def at_import_transitive(a, b), do: ex_dbgi_defguard_x_use_injected_snoc(a, b) # @import_transitive
end

