# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XUseInjected.ImportOnly2 do
  import ExDbgi.Defguard.XUseInjected, only: [ex_dbgi_defguard_x_use_injected_snoc: 1] # @import_only_2_key

  def at_import_only_2(a, b), do: ex_dbgi_defguard_x_use_injected_snoc(a, b) # @import_only_2
end
