package org.elixir_lang.expander

import org.elixir_lang.language_level.ElixirLanguageFeature.FUNCTION_ERRORS_CONTINUE
import org.elixir_lang.language_level.ElixirLanguageLevel

/**
 * The message Elixir gives for each error [Expansion.Error] can name, as one pattern matching every supported
 * release's wording.
 */
object ErrorKinds {
    private const val PARENS_MAP_LOOKUP =
        """\. If you want to do a map lookup instead, please remove parens from """

    /** Where a remote call isn't allowed, as each release names a guard or a bitstring size. */
    private const val GUARD = """(guards|a guard|bitstring size specifier|a bitstring size specifier)"""

    /** How a rejected remote call begins, and from 1.19, for a macro, the `require` it lacks; 1.19.5 omits a space. */
    private const val CANNOT_INVOKE = """(cannot invoke remote function|you must require the module ?\S+ before invoking macro)"""

    /** The four kinds of definition. */
    private const val DEFINER = """(def|defp|defmacro|defmacrop)"""

    private val PATTERNS = mapOf(
        // elixir_expand
        "undefined_var" to """^undefined variable "[^"]+"( \(context [^)]+\))?$""",
        "undefined_var_bang" to
            """^expected "[^"]+"( \(context [^)]+\))? to expand to an existing variable or be part of a match$""",
        "undefined_var_pin" to
            """^undefined variable \^\S+\. No variable "[^"]+"( \(context [^)]+\))? has been defined before the current pattern$""",
        "invalid_arg_for_pin" to """^invalid argument for unary operator \^, expected an existing variable, got: \^""",
        "pin_outside_of_match" to
            """^(cannot use \^.* outside of match clauses|misplaced operator \^.*The pin operator \^ is supported only inside matches)""",
        "unbound_underscore" to """^invalid use of _\. ("_" represents a value to be ignored|_ can only be used inside patterns)""",
        "invalid_expr_in_guard" to """^invalid expression in guards?, .+ is not allowed in guards\. To learn more about guards""",
        "invalid_expr_in_bitsize" to
            """^.+ is not allowed (inside a |in )?bitstring size specifier\. The size specifier in matches works like guards\.""",
        "parallel_bitstring_match" to """^binary patterns cannot be matched in parallel using "=", excess pattern: """,
        "unhandled_arrow_op" to """^(unhandled|misplaced) operator ->""",
        "unhandled_type_op" to """^misplaced operator ::/2\n\nThe :: operator is typically used in bitstrings""",
        "unhandled_cons_op" to """^misplaced operator \|/2\n\nThe \| operator is typically used between brackets""",
        "__cursor__" to """^reserved special form __cursor__ cannot be expanded""",
        "invalid_call" to """^invalid call """,
        // `|` and `::` outside their constructs are local calls up to 1.14, with 1.15's misplaced-operator wording.
        // After the module body, an undefined local call names the module, or the function the compiler generates.
        "undefined_function" to
            """^(undefined function \S+/\d+( \((there is no such import|""" +
            """expected .+ to define such a function or for it to be imported, but none are available|""" +
            """this function is auto-generated by the compiler and must always be called as a remote, as in __MODULE__\.\S+/\d+)\))?$|""" +
            """misplaced operator (\||::)/2\n\nThe (\||::) operator is typically used)""",
        "undefined_local_capture" to """^undefined function \S+/\d+( \(there is no such import\))?$""",
        "invalid_expr_in_scope" to """^cannot invoke \S+ outside \S+$""",
        "op_ambiguity" to """^".+" looks like a function call but there is a variable named ".+"""",
        "parens_map_lookup_guard" to "^cannot invoke remote function in guard$PARENS_MAP_LOOKUP",
        "parens_map_lookup" to "^cannot invoke remote function (in|inside) $GUARD$PARENS_MAP_LOOKUP",
        "invalid_function_call" to """^invalid function call :\S+\.\(\)$""",
        "invalid_clauses" to """^the function "\S+" cannot handle clauses with the -> operator because it is not a macro""",
        "caller_not_allowed" to """^__CALLER__ is available only inside defmacro and defmacrop$""",
        "env_not_allowed" to """^__ENV__ is not allowed inside a match$""",
        "missing_option" to """^missing :\S+ option in "\w+"$""",
        "invalid_args" to """^invalid arguments for "\w+"$""",
        "invalid_pattern_in_match" to """^invalid pattern in match, .+ is not allowed in matches$""",
        "stacktrace_not_allowed" to
            """^__STACKTRACE__ is available only inside catch and rescue clauses of try expressions$""",
        "underscore_in_cond" to """^invalid use of _ inside "cond"\. If you want the last clause to always match""",
        "invalid_alias" to """^invalid alias: ".+"\. If you wanted to define an alias, an alias must expand to an atom""",
        "expected_compile_time_module" to
            """^invalid argument for (alias|require|import), expected a compile time atom or alias, got: """,
        "as_in_multi_alias_call" to """^:as option is not supported by multi-alias call$""",
        "unsupported_option" to """^unsupported option \S+ given to (alias|require|import|quote|for)$""",
        "options_are_not_keyword" to
            """^invalid options for (alias|require|import|quote), expected a keyword list, got: """,
        "unquote_outside_quote" to """^unquote(_splicing)? called outside quote$""",
        "invalid_bind_quoted_for_quote" to
            """^invalid :bind_quoted for quote, expected a keyword list of variable names, got: """,
        "quote_in_pattern_with_unquote" to """^unquote is not allowed when quote is used inside a pattern or guard""",
        "for_invalid_uniq" to """^:uniq option for comprehensions only accepts a boolean, got: """,
        "for_conflicting_reduce_into_uniq" to """^cannot use :reduce alongside :into/:uniq in comprehension$""",
        "for_generator_start" to """^for comprehensions must start with a generator$""",
        "for_without_reduce_bad_block" to
            """^the do block was written using acc -> expr clauses but the :reduce option was not given$""",
        "for_with_reduce_bad_block" to
            """^when using :reduce with comprehensions, the do block must be written using acc -> expr clauses, where each clause expects the accumulator as a single argument$""",
        "invalid_local_invocation" to
            """^cannot find or invoke local \S+/\d+ inside (a )?(match|guards?|bitstring size specifier)\. """ +
            """Only macros can be invoked (in|inside) a (match|guards?|bitstring size specifier) and they must be defined before their invocation\. """,
        // elixir_def
        "invalid_function_head" to
            """^(only variables and \\\\ are allowed as arguments in function head\.|""" +
            """(patterns|guards) are not allowed in function head, only variables and default arguments \(using \\\\\))""",
        "invalid_def" to """^invalid syntax in (def|defp|defmacro|defmacrop) """,
        "no_alias" to """^function names should start with lowercase characters or underscore, invalid name .+$""",
        "__info__" to """^cannot define (def|defp|defmacro|defmacrop) __info__/1 as it is automatically defined by Elixir$""",
        "module_info" to
            """^cannot define (def|defp|defmacro|defmacrop) module_info/[01] as it is automatically defined by Erlang$""",
        "is_record" to
            """^cannot define (def|defp) is_record/2 due to compatibility (issues )?with the Erlang compiler \(it is a known limitation\)$""",
        "function_head" to """^implementation not provided for predefined $DEFINER \S+/\d+$""",
        "changed_kind" to """^$DEFINER \S+/\d+ already defined as $DEFINER in \S+:\d+$""",
        // From 1.19 the text goes on to name the earlier clause's line.
        "duplicate_defaults" to
            """^$DEFINER \S+/\d+ defines defaults multiple times\. Elixir allows defaults to be declared once per definition\.""",
        "defs_with_defaults" to """^$DEFINER \S+/\d+ (defaults conflicts with|conflicts with defaults from) \S+/\d+$""",
        // elixir_locals, and Module.Types from 1.18
        "incorrect_dispatch" to """^cannot invoke macro \S+/\d+ before its definition$""",
        // elixir_module
        "invalid_module_name" to """^invalid module name: """,
        "module_reserved" to """^module \S+ is reserved and cannot be defined$""",
        "module_in_definition" to """^cannot define module \S+ because it is currently being defined in """,
        // Module's ArgumentErrors for a written attribute value
        "invalid_attribute_value" to
            """^(@\S+ is a built-in module attribute |@behaviour expects a module, got: |""" +
            """the @on_load attribute can only be set once per module$|invalid value for @dialyzer attribute: |""" +
            """attributes type, typep, opaque, spec, callback, and macrocallback must be set directly via the @ notation$)""",
        // A function `@on_load`, `@dialyzer`, `@nifs` or `@compile :inline` names, in each release's wording
        "undefined_attribute_function" to
            """^(undefined function \S+/\d+ given to @\S+( :\S+)?|@on_load function \S+/\d+ is undefined|""" +
            """inlined function \S+/\d+ undefined)$""",
        "wrong_kind_attribute_function" to
            """^(macro \S+/\d+ given to @\S+( :\S+)? \((only functions are supported|@dialyzer only supports function annotations)\)|""" +
            """expected @on_load function \S+/\d+ to be (a function|defined as "def"), got "\S+")$""",
        // elixir_errors: a module whose errors were logged, from 1.15
        "compile_error" to """^cannot compile module .+ \(errors have been logged\)$""",
        // Kernel's ArgumentErrors, and before 1.20.0-rc.2 the FunctionClauseError of a `defmodule` with other blocks
        "definer_outside_module" to """^cannot invoke (def|defp|defmacro|defmacrop)/2 outside module$""",
        "definer_inside_function" to """^cannot invoke (def|defp|defmacro|defmacrop)/2 inside function/macro$""",
        "definer_in_match" to
            """^invalid expression in match, (def|defp|defmacro|defmacrop|defmodule)/2 is not allowed in patterns """,
        "definer_in_guard" to
            """^invalid expression in guard, (def|defp|defmacro|defmacrop|defmodule)/2 is not allowed in guards\. """,
        "attribute_outside_module" to """^cannot invoke @/1 outside module$""",
        "attribute_in_match_or_guard" to
            """^(invalid write attribute syntax\. If you want to define an attribute, don't do this:|""" +
            """invalid usage of module attributes\. Module attributes cannot be used inside pattern matching \(and guards\) outside of a function\.)""",
        "attribute_set_in_function" to """^cannot set attribute @\S+ inside function/macro$""",
        "behavior_attribute" to """^@behavior attribute is not supported, please use @behaviour instead$""",
        "attribute_arity" to """^expected 0 or 1 argument for @\S+, got:? \d+""",
        "reserved_word" to
            """^(unexpected reserved word at the top-level of the "defmodule .+" do-block: |""" +
            """no function clause matching in Kernel\.defmodule/2)""",
        // elixir_quote's ArgumentErrors
        "quote_unquote_splicing" to
            """^unquote_splicing only works inside arguments and block contexts, wrap it in parens if you want it to work with one-liners$""",
        "quote_invalid_runtime_option" to """^invalid runtime value for option :(unquote|generated) in quote, got: """,
        // Kernel's macros
        "var_bang_not_a_variable" to """^expected a variable to be given to var!, got: """,
        "var_bang_context_not_atom" to """^expected var! context to expand to an atom, got: """,
        "alias_bang_function_clause" to """^no function clause matching in Kernel\.alias!/1""",
        // elixir_dispatch
        "macro_conflict" to
            """^call to local macro \S+/\d+ conflicts with imported \S+\.\S+/\d+, please rename the local macro or remove the conflicting import$""",
        "ambiguous_call" to
            """^(function \S+ imported from both \S+ and \S+, call is ambiguous|conflicting \S+ import from modules \S+ and \S+)""",
        "unrequired_module" to """^you must require \S+ before invoking the macro \S+$""",
        // elixir_rewrite
        "invalid_match" to "^$CANNOT_INVOKE \\S+ inside a match$",
        "invalid_match_append" to
            """^invalid argument for \+\+ operator inside a match, expected a literal proper list, got: """,
        "invalid_guard" to "^$CANNOT_INVOKE \\S+ inside $GUARD$",
        // elixir_aliases
        "invalid_alias_module" to """^alias cannot be inferred automatically for module: .+, please use the :as option""",
        "invalid_alias_for_as" to """^invalid value for option :as, expected (an alias, got: |a simple alias, got nested alias: )""",
        "unloaded_module" to """^module \S+ is not loaded and could not be found$""",
        "scheduled_module" to """^module \S+ is not loaded but was defined\.""",
        "circular_module" to """^you are trying to use(/import/require)? the module \S+ which is currently being defined""",
        // elixir_import
        "invalid_option" to
            """^invalid :(only|except) option for import, expected (a keyword list with integer values$|value to be )""",
        "only_and_except_given" to """^:only and :except can only be given together to import when :only is """,
        "duplicated_import" to """^invalid :(only|except) option for import, \S+/\d+ is duplicated$""",
        "invalid_import" to """^cannot import \S+ because it is undefined or private$""",
        "special_form_conflict" to """^cannot import \S+ because it conflicts with Elixir special forms""",
        "no_macros" to """^could not load macros from module \S+$""",
        // `elixir_locals`' `function_conflict` up to 1.17
        "import_conflict" to """^imported \S+ conflicts with local function$""",
        // elixir_clauses
        "recursive" to """^(recursive|cyclic) variable definition in patterns:\n\n""",
        "bad_or_missing_clauses" to
            """^(expected -> clauses for :\w+ in "\w+"|invalid "\w+" block in "\w+", it expects "pattern -> expr" clauses)$""",
        "duplicated_clauses" to """^duplicated? (:\w+|"\w+") clauses given for "\w+"$""",
        "unexpected_option" to """^unexpected option :\w+ in "\w+"$""",
        "wrong_number_of_args_for_clause" to
            """^expected (one argument|one or two args) for (:\w+|"\w+") clauses \(->\) in "\w+"$""",
        "multiple_after_clauses_in_receive" to """^expected a single -> clause for :after in "receive"$""",
        "invalid_rescue_clause" to
            """^invalid "rescue" clause\. The clause should match on an alias, a variable or be in the "var in \[alias\]" format""",
        // elixir_fn
        "defaults_in_args" to """^anonymous functions cannot have optional arguments$""",
        "clauses_with_different_arities" to """^cannot mix clauses with different arities in anonymous functions$""",
        "capture_arg_outside_of_capture" to
            """^(unhandled &\d+ outside of a capture|capture argument &\d+ must be used within the capture operator &)$""",
        "unallowed_capture_arg" to """^capture &-?\d+ is not allowed$""",
        "invalid_arity_for_capture" to
            """^(invalid arity for &, expected a number between 0 and 255, got: -?\d+|capture argument &-?\d+ must be numbered between 1 and 255)$""",
        "capture_arg_without_predecessor" to """^capture (argument )?&\d+ cannot be defined without &\d+""",
        "invalid_args_for_capture" to """^invalid args for &, expected """,
        "block_expr_in_capture" to
            """^(invalid args for &, block expressions are not allowed, got: |block expressions are not allowed inside the capture operator &, got: )""",
        "nested_capture" to """^nested captures (via & )?are not allowed""",
        // elixir_map
        "repeated_key" to """^key .+ will be overridden in map$""",
        "update_syntax_in_wrong_context" to """^cannot use map/struct update syntax in (match|guard), got: """,
        "not_kv_pair" to """^expected key-value pairs in a map, got: """,
        "invalid_variable_in_map_key_match" to
            """^cannot use variable \S+ as map key inside a pattern\. Map keys in patterns can only be literals""",
        "invalid_pin_in_map_key_match" to
            """^cannot use pin operator \^\S+ inside a data structure as a map key in a pattern\.""",
        // `__struct__/0` in an update or a match up to 1.17.
        "undefined_struct" to """^\S+\.__struct__/[01] is undefined, cannot expand struct \S+\.""",
        "inaccessible_struct" to
            """^cannot access struct \S+, the struct was not yet defined or the struct is being accessed in the same context that defines it$""",
        "invalid_struct_name" to """^expected struct name to be a compile time atom or alias, got: """,
        "invalid_struct_name_in_match" to
            """^expected struct name in a match to be a compile time atom, alias or a variable, got: """,
        "invalid_key_for_struct" to """^invalid key .+ for struct, struct keys must be atoms, got: """,
        "unknown_key_for_struct" to """^unknown key \S+ for struct \S+$""",
        // The `KeyError` and `ArgumentError` the struct's `__struct__/1` raises.
        "struct_unknown_key" to """^key \S+ not found""",
        "struct_missing_enforced_keys" to """^the following keys must also be given when building struct \S+: \[""",
        // elixir_bitstring
        "unsized_binary" to
            """^a binary field without size is only allowed at the end of a binary pattern, at the right side of binary concatenation and (and )?never allowed in binary generators""",
        "unaligned_binary" to """^expected .+ to be a binary but its number of bits is not divisible by 8$""",
        "unknown_match" to """^a bitstring only accepts binaries, numbers, and variables inside a match, got: """,
        "nested_match" to """^cannot pattern match inside a bitstring that is already in match, got: """,
        "bittype_mismatch" to """^conflicting \w+ specification for bit field: ".*" and ".*"$""",
        "undefined_bittype" to """^unknown bitstring specifier: """,
        "bad_unit_argument" to """^unit in bitstring expects an integer as argument, got: """,
        "bittype_literal_bitstring" to """^literal <<>> in bitstring supports only type specifiers""",
        "bittype_literal_string" to """^literal string in bitstring supports only endianness and type specifiers""",
        "bittype_utf" to """^size and unit are not supported on utf types$""",
        "bittype_signed" to """^signed and unsigned specifiers are supported only on integer and float types$""",
        "bittype_float_size" to """^float requires size\*unit to be (16, 32, or 64|32 or 64) \(default\), got: """,
        "bittype_unit" to """^integer and float types require a size specifier if the unit specifier is given$""",
        "invalid_literal" to """^invalid literal .+ in <<>>$""",
        "bad_size_argument" to """^size in bitstring expects an integer or a variable as argument, got: """,
        "undefined_var_in_spec" to """^undefined variable ".+" in bitstring segment\. If the size of the binary is a variable""",
    ).mapValues { (_, pattern) -> Regex(pattern, RegexOption.DOT_MATCHES_ALL) }

    /** The kinds Elixir raises at expansion as an exception other than `CompileError`, whose message has no line. */
    private val WITHOUT_LINE = setOf(
        "quote_unquote_splicing",
        "quote_invalid_runtime_option",
        "var_bang_not_a_variable",
        "var_bang_context_not_atom",
        "alias_bang_function_clause",
        "struct_unknown_key",
        "struct_missing_enforced_keys",
        "compile_error",
        "definer_outside_module",
        "definer_inside_function",
        "definer_in_match",
        "definer_in_guard",
        "reserved_word",
        "attribute_outside_module",
        "attribute_in_match_or_guard",
        "attribute_set_in_function",
        "behavior_attribute",
        "attribute_arity",
        "invalid_attribute_value",
    )

    fun pattern(kind: String): Regex = PATTERNS[kind] ?: throw AssertionError("no message pattern for error $kind")

    /**
     * Whether Elixir at [level] reports [kind] with a line: an invalid module name is a `CompileError` with one up to
     * 1.14, and an `ArgumentError` from 1.15.
     */
    fun hasLine(kind: String, level: ElixirLanguageLevel): Boolean =
        kind !in WITHOUT_LINE && !(kind == "invalid_module_name" && FUNCTION_ERRORS_CONTINUE.isSufficient(level))
}
