# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateUnresolvable.XArity do
  alias ExDbgi.DefdelegateUnresolvable.XArity
  alias ExDbgi.DefdelegateUnresolvable.XArity, as: Aliased
  import ExDbgi.DefdelegateUnresolvable.XArity

  def at_qualified(a, b), do: ExDbgi.DefdelegateUnresolvable.XArity.ex_dbgi_defdelegate_unresolvable_x_arity_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArity.ex_dbgi_defdelegate_unresolvable_x_arity_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defdelegate_unresolvable_x_arity_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defdelegate_unresolvable_x_arity_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defdelegate_unresolvable_x_arity_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.DefdelegateUnresolvable.XArity.ex_dbgi_defdelegate_unresolvable_x_arity_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExDbgi.DefdelegateUnresolvable.XArity."ex_dbgi_defdelegate_unresolvable_x_arity_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExDbgi.DefdelegateUnresolvable.XArity."ex_dbgi_defdelegate_unresolvable_x_arity_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExDbgi.DefdelegateUnresolvable.XArity, :ex_dbgi_defdelegate_unresolvable_x_arity_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExDbgi.DefdelegateUnresolvable.XArity, :"ex_dbgi_defdelegate_unresolvable_x_arity_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExDbgi.DefdelegateUnresolvable.XArity", :ex_dbgi_defdelegate_unresolvable_x_arity_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExDbgi.DefdelegateUnresolvable.XArity, :"#{a}ex_dbgi_defdelegate_unresolvable_x_arity_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExDbgi.DefdelegateUnresolvable.XArity, pick(b, :ex_dbgi_defdelegate_unresolvable_x_arity_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExDbgi.DefdelegateUnresolvable.XArity, pick(b, :"ex_dbgi_defdelegate_unresolvable_x_arity_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExDbgi.DefdelegateUnresolvable.XArity, :"ex_dbgi_defdelegate_unresolvable_x_arity_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExDbgi.DefdelegateUnresolvable.XArity", :ex_dbgi_defdelegate_unresolvable_x_arity_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExDbgi.DefdelegateUnresolvable.XArity, :"#{a}ex_dbgi_defdelegate_unresolvable_x_arity_snoc", 2}, a, b} # @mfa_interpolated
  def at_arity_3(a, b), do: ExDbgi.DefdelegateUnresolvable.XArity.ex_dbgi_defdelegate_unresolvable_x_arity_snoc(a, b, a) # @arity_3
  def at_unqualified_arity_3(a, b), do: ex_dbgi_defdelegate_unresolvable_x_arity_snoc(a, b, a) # @unqualified_arity_3

  defp pick(opts, key), do: opts[key]
end
