# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defguard.W2.ImportExceptFunctions2 do
  import ExGen.Defguard.W2, except: [ex_gen_defguard_w2_snoc: 1], only: :functions # @import_except_functions_2_key

  def at_import_except_functions_2(a, b), do: ex_gen_defguard_w2_snoc(a, b) # @import_except_functions_2
end
