# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defguard.W2.ImportFunctionsExcept2 do
  import ExGen.Defguard.W2, only: :functions, except: [ex_gen_defguard_w2_snoc: 1] # @import_functions_except_2_key

  def at_import_functions_except_2(a, b), do: ex_gen_defguard_w2_snoc(a, b) # @import_functions_except_2
end
