# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XArity do
  alias ExGen.Def.XArity
  alias ExGen.Def.XArity, as: Aliased
  import ExGen.Def.XArity

  def at_qualified(a, b), do: ExGen.Def.XArity.ex_gen_def_x_arity_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArity.ex_gen_def_x_arity_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_def_x_arity_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_def_x_arity_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_def_x_arity_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExGen.Def.XArity.ex_gen_def_x_arity_snoc/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExGen.Def.XArity."ex_gen_def_x_arity_snoc"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExGen.Def.XArity."ex_gen_def_x_arity_snoc"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExGen.Def.XArity, :ex_gen_def_x_arity_snoc, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExGen.Def.XArity, :"ex_gen_def_x_arity_snoc", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExGen.Def.XArity", :ex_gen_def_x_arity_snoc, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExGen.Def.XArity, :"#{a}ex_gen_def_x_arity_snoc", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExGen.Def.XArity, pick(b, :ex_gen_def_x_arity_snoc), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExGen.Def.XArity, pick(b, :"ex_gen_def_x_arity_snoc"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExGen.Def.XArity, :"ex_gen_def_x_arity_snoc", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExGen.Def.XArity", :ex_gen_def_x_arity_snoc, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExGen.Def.XArity, :"#{a}ex_gen_def_x_arity_snoc", 2}, a, b} # @mfa_interpolated
  def at_arity_3(a, b), do: ExGen.Def.XArity.ex_gen_def_x_arity_snoc(a, b, a) # @arity_3
  def at_unqualified_arity_3(a, b), do: ex_gen_def_x_arity_snoc(a, b, a) # @unqualified_arity_3

  defp pick(opts, key), do: opts[key]
end
