# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XNfc do
  alias ExGen.Def.XNfc
  alias ExGen.Def.XNfc, as: Aliased
  import ExGen.Def.XNfc

  def at_qualified(a, b), do: ExGen.Def.XNfc.ex_gen_def_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.ex_gen_def_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_def_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_def_x_nfc_snoć(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_def_x_nfc_snoć(b) # @pipe
  def at_capture(a, b), do: {&ExGen.Def.XNfc.ex_gen_def_x_nfc_snoć/2, a, b} # @capture
  def at_qualified_quoted(a, b), do: ExGen.Def.XNfc."ex_gen_def_x_nfc_snoć"(a, b) # @qualified_quoted
  def at_capture_quoted(a, b), do: {&ExGen.Def.XNfc."ex_gen_def_x_nfc_snoć"/2, a, b} # @capture_quoted
  def at_apply(a, b), do: apply(ExGen.Def.XNfc, :ex_gen_def_x_nfc_snoć, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(ExGen.Def.XNfc, :"ex_gen_def_x_nfc_snoć", [a, b]) # @apply_quoted
  def at_apply_module_quoted(a, b), do: apply(:"Elixir.ExGen.Def.XNfc", :ex_gen_def_x_nfc_snoć, [a, b]) # @apply_module_quoted
  def at_apply_interpolated(a, b), do: apply(ExGen.Def.XNfc, :"#{a}ex_gen_def_x_nfc_snoć", [a, b]) # @apply_interpolated
  def at_apply_nested(a, b), do: apply(ExGen.Def.XNfc, pick(b, :ex_gen_def_x_nfc_snoć), [a, b]) # @apply_nested
  def at_apply_nested_quoted(a, b), do: apply(ExGen.Def.XNfc, pick(b, :"ex_gen_def_x_nfc_snoć"), [a, b]) # @apply_nested_quoted
  def at_mfa_quoted(a, b), do: {{ExGen.Def.XNfc, :"ex_gen_def_x_nfc_snoć", 2}, a, b} # @mfa_quoted
  def at_mfa_module_quoted(a, b), do: {{:"Elixir.ExGen.Def.XNfc", :ex_gen_def_x_nfc_snoć, 2}, a, b} # @mfa_module_quoted
  def at_mfa_interpolated(a, b), do: {{ExGen.Def.XNfc, :"#{a}ex_gen_def_x_nfc_snoć", 2}, a, b} # @mfa_interpolated
  def at_atom(a, b), do: {:ex_gen_def_x_nfc_snoć, a, b} # @atom

  defp pick(opts, key), do: opts[key]
end
