# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacrop.XDefaultsHead.ImportOnlyPrivate do
  import Src.Defmacrop.XDefaultsHead, only: [src_defmacrop_x_defaults_head_snoc: 1] # @import_only_private_key


end
