# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacrop.XUseInjected.ImportOnlyPrivate do
  import Src.Defmacrop.XUseInjected, only: [src_defmacrop_x_use_injected_snoc: 1] # @import_only_private_key


end
