# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.EexFunctionFromKind.XOtherModule do
  alias ExGen.EexFunctionFromKind.XOtherModule
  alias ExGen.EexFunctionFromKind.XOtherModule, as: Aliased
  import ExGen.EexFunctionFromKind.XOtherModule

  def at_qualified(a, b), do: ExGen.EexFunctionFromKind.XOtherModule.ex_gen_eex_function_from_kind_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.ex_gen_eex_function_from_kind_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_eex_function_from_kind_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_eex_function_from_kind_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_eex_function_from_kind_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExGen.EexFunctionFromKind.XOtherModule.ex_gen_eex_function_from_kind_x_other_module_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExGen.EexFunctionFromKind.XOtherModule, :ex_gen_eex_function_from_kind_x_other_module_snoc, [a, b]) # @apply
  def at_other_qualified(a, b), do: ExGen.EexFunctionFromKind.XOtherModule.Other.ex_gen_eex_function_from_kind_x_other_module_snoc(a, b) # @other_qualified
end
