package org.elixir_lang

import com.intellij.psi.PsiNamedElement
import com.intellij.psi.PsiPolyVariantReference
import com.intellij.psi.ResolveResult
import com.intellij.psi.ResolveState
import com.intellij.psi.util.isAncestor
import com.intellij.util.concurrency.annotations.RequiresReadLock
import org.elixir_lang.errorreport.Logger
import org.elixir_lang.psi.CallDefinitionClause
import org.elixir_lang.psi.CallDefinitionClause.enclosingModularMacroCall
import org.elixir_lang.psi.call.Call
import org.elixir_lang.psi.call.qualification.Qualified
import org.elixir_lang.psi.impl.ElixirPsiImplUtil
import org.elixir_lang.psi.impl.call.qualification.qualifiedToModulars

fun safeMultiResolve(reference: PsiPolyVariantReference, incompleteCode: Boolean): Array<ResolveResult> =
    try {
        reference.multiResolve(incompleteCode)
    } catch (stackOverflowError: StackOverflowError) {
        Logger.error(
            PsiPolyVariantReference::class.java,
            "StackOverflow resolving reference",
            reference.element,
            stackOverflowError
        )

        emptyArray()
    }

/**
 * Calls currently having their macro-ness decided by [resolvesToMacro], per thread.
 *
 * Resolving a call to decide whether its arguments are variable declarations re-enters variable
 * resolution, which can ask the same question about the same call. [resolvesToModularName] has the
 * same hazard and guards it with the `ENTRANCE` of a `ResolveState`; the callers here hold no
 * `ResolveState`, so the guard is kept beside the function instead of widening their signatures.
 */
private val RESOLVING_MACRO: ThreadLocal<MutableSet<Call>> = ThreadLocal.withInitial { mutableSetOf<Call>() }

/**
 * Whether [call] resolves to a `defmacro` rather than a `def`.
 *
 * A macro's arguments are quoted, so in a match they can bind, while a function's arguments are
 * values and bind nothing. The two are indistinguishable syntactically, so
 * [org.elixir_lang.reference.Callable.isVariable] has to resolve the call to tell them apart.
 *
 * Answers `false` rather than guessing when the call does not resolve - a macro from a `.beam`
 * dependency, or one generated by `Record.defrecord` or injected by `use`, may not resolve at all.
 * That keeps the unresolved case behaving exactly as it did before
 * [#305](https://github.com/intellij-elixir/intellij-elixir/issues/305): not a declaration.
 */
fun resolvesToMacro(call: Call): Boolean {
    val inProgress = RESOLVING_MACRO.get()

    // already deciding this same call further up the stack, so don't recurse into it again
    if (!inProgress.add(call)) return false

    return try {
        (call.reference as? PsiPolyVariantReference)
            ?.let { safeMultiResolve(it, false) }
            ?.any { resolveResult ->
                resolveResult.isValidResult &&
                        (resolveResult.element as? Call)?.let { resolved ->
                            CallDefinitionClause.isMacro(resolved) &&
                                    // don't treat the signature as a call of the macro
                                    !resolved.isAncestor(call)
                        } == true
            }
            ?: false
    } finally {
        inProgress.remove(call)
    }
}

/**
 * Whether [call]'s own reference resolves to a `defmacro` enclosed by the module named [modularName].
 *
 * [org.elixir_lang.psi.ModuleWalker.definers]/`matches` now answer this same question structurally, from
 * [org.elixir_lang.psi.CallableTable] outward, for every enclosing scope that has one - [resolvesToModularCalls]
 * is their live fallback: while no enclosing table can be consulted yet (mid-build, see
 * [org.elixir_lang.psi.CallableTable.ofOrNull]). A compiled (`.beam`) target reaches
 * [org.elixir_lang.psi.CallableTable.matchesCompiledIn] instead once a table exists - this function's own
 * `resolveResult.element?.let { it as? Call }` still discards a `BeamCallDefinition` match, same as before,
 * since it has no enclosing-scope table to search. [resolvesToQualifiedModularName] is the counterpart for
 * a call that is always written qualified.
 */
fun resolvesToModularName(call: Call, state: ResolveState, modularName: String): Boolean =
        // A boolean answer only needs the first match - `.any` on a `Sequence` short-circuits there, unlike
        // `resolvesToModularCalls`'s `.mapNotNull` over the full `Array`, which every candidate call site
        // that wants the actual `Call`s (not just yes/no) legitimately needs to walk in full.
        if (!isBeingResolved(call, state)) {
            call.reference?.let { it as PsiPolyVariantReference }?.let { reference ->
                safeMultiResolve(reference, false).asSequence().any { resolveResult ->
                    resolveResult.isValidResult && matchedModularCall(resolveResult, call, modularName) != null
                }
            } ?: false
        } else {
            false
        }

/**
 * [resolvesToModularName], returning the matched [Call]s instead of collapsing them to a [Boolean] - for a
 * caller like `Schema.walkChild` that needs an actual [Call] to walk into, not just a yes/no answer.
 */
internal fun resolvesToModularCalls(call: Call, state: ResolveState, modularName: String): kotlin.collections.List<Call> =
        // it is not safe to call `multiResolve` on the call's reference if that `call` is currently being resolved.
        if (!isBeingResolved(call, state)) {
            call.reference?.let { it as PsiPolyVariantReference }?.let { reference ->
                safeMultiResolve(reference, false).mapNotNull { resolveResult ->
                    if (resolveResult.isValidResult) {
                        matchedModularCall(resolveResult, call, modularName)
                    } else {
                        null
                    }
                }
            } ?: emptyList()
        } else {
            emptyList()
        }

/** Shared filter both [resolvesToModularName] and [resolvesToModularCalls] apply to a resolve candidate. */
private fun matchedModularCall(resolveResult: ResolveResult, call: Call, modularName: String): Call? =
        resolveResult.element?.let { it as? Call }?.takeIf { resolved ->
            CallDefinitionClause.isMacro(resolved) &&
                    // don't treat the signature as a call of the function
                    !resolved.isAncestor(call) &&
                    enclosingModularMacroCall(resolved)?.name == modularName
        }

/**
 * Whether [call] is somewhere on the stack of the resolve currently in progress - resolving [call]'s own
 * reference again here would recurse. [org.elixir_lang.EEx]/[org.elixir_lang.psi.mix.Generator] guard their
 * qualified-call path with this directly: resolving a qualified call's *qualifier* can walk back up through
 * the enclosing module and re-visit the same call as one of its `CallableTable` live candidates.
 */
internal fun isBeingResolved(call: Call, state: ResolveState): Boolean =
        call.isEquivalentTo(state.get(ElixirPsiImplUtil.ENTRANCE)) || qualifierIsBeingResolved(call, state)

/**
 * [resolvesToModularName], for a call real Elixir always writes qualified (`EEx`, `Mix.Generator`'s
 * macros): a qualified call's own qualifier resolves via [qualifiedToModulars] (alias resolution, the same
 * mechanism `import`/`use` use to find their own target module), never by resolving the call itself, so
 * this reaches a compiled (`.beam`) target. The exotic, non-idiomatic unqualified case (e.g. `import EEx`)
 * falls back to [resolvesToModularName] live, exactly as before either form had this qualified path.
 * [isBeingResolved] guards it the same way [resolvesToModularName] guards its own reference resolution:
 * resolving the qualifier can walk back up through the enclosing module and revisit [call] itself as one
 * of `CallableTable`'s live candidates - without the guard, that recurses.
 */
@RequiresReadLock
fun resolvesToQualifiedModularName(call: Call, state: ResolveState, modularName: String): Boolean =
    if (call is Qualified) {
        !isBeingResolved(call, state) &&
            call.qualifiedToModulars().any { (it as? PsiNamedElement)?.name == modularName }
    } else {
        resolvesToModularName(call, state, modularName)
    }

private fun qualifierIsBeingResolved(call: Call, state: ResolveState): Boolean =
        if (call is Qualified) {
            // `isAncestor` rejects a null second argument, and a caller with no entrance has nothing
            // for the guard to compare against.
            state.get(ElixirPsiImplUtil.ENTRANCE)?.let { entrance ->
                call.qualifier().isAncestor(entrance, strict = false)
            } ?: false
        } else {
            false
        }
